// Opt-in public fixture. Real UI → IPC, no interception of Tauri/HTTP/credentials.
(async()=>{
 const details={stage:'open',checks:[],layer:'packaged production UI/IPC; synthetic input plus native keyboard/focus/layout observation'};
 const check=(ok,name)=>{if(!ok)throw Error(name);details.checks.push(name);};
 const call=async(operation,payload={})=>{const r=await window.__TAURI_INTERNALS__.invoke('core_request',{request:{protocolVersion:1,requestId:crypto.randomUUID(),operation,payload}});if(!r.ok)throw Object.assign(Error(r.error.message),{code:r.error.code});return r.value;};
 const read=(op,p={})=>window.__loomlightProbeRetryBusy(()=>call(op,p));
 const wait=async fn=>{const start=performance.now();while(!await fn()){if(performance.now()-start>20000)throw Error('Timeout at '+details.stage);await new Promise(r=>setTimeout(r,40));}};
 const find=window.__loomlightProbeFindButton;const root=()=>document.querySelector('.prompt-preparation');
 const click=async(label,expectedCode)=>{await wait(()=>find(label)&&!find(label).disabled);const before=Number(root()?.dataset.mutationSequence??0);const previewBefore=Number(root()?.dataset.previewSequence??0);find(label).click();if(['Save prompt','Confirm restore baseline','Undo project change','Redo project change'].includes(label)){await wait(()=>Number(root()?.dataset.mutationSequence??0)>before);check(root().dataset.mutationOutcome===(expectedCode?'refused':'committed')&&(!expectedCode||root().dataset.errorCode===expectedCode),'UI mutation outcome '+label+(expectedCode?' refusal':''));}else if(label==='Build context preview'){await wait(()=>Number(root()?.dataset.previewSequence??0)>previewBefore);check(root().dataset.previewOutcome===(expectedCode?'refused':'prepared')&&(!expectedCode||root().dataset.errorCode===expectedCode),'UI preview outcome '+(expectedCode??'prepared'));}await wait(()=>root()?.dataset.busy!=='true');};
 const input=(name,value)=>{const n=document.querySelector(`.prompt-preparation [name="${name}"]`);if(!n)throw Error('Missing input');n.focus();n.value=value;n.dispatchEvent(new Event('input',{bubbles:true}));};
 const pause=async stage=>{details.stage=stage;await call('probe.promptStage',{stage,announce:true});const start=performance.now();while(!(await read('probe.promptStage',{stage})).done){if(performance.now()-start>180000)throw Error('Observation timeout at '+stage);await new Promise(r=>setTimeout(r,200));}};
 const open=async()=>{document.querySelector('.shell-settings').click();await click('Current project');await wait(()=>root()?.dataset.busy==='false');};
 let project;
 try{
  await click('Source foundation fixture');await wait(()=>document.querySelector('.scene-workspace'));project=await read('project.current');const payload=()=>({sessionId:project.sessionId});const prompt=()=>read('prompts.list',payload());
  const inventory=await read('source.list',payload());const sourceBefore=await Promise.all(inventory.files.map(f=>read('source.open',{...payload(),path:f.path})));
  await open();
  if(window.__loomlightPromptPhase===2){check((await prompt()).customized===false,'Process reopen preserves confirmed baseline restore');check(document.querySelector('[name="systemPrompt"]').value===(await prompt()).baselineText,'Process reopen displays actual installed baseline');await click('Context preparation');for(const c of document.querySelectorAll('.context-references input:not(:disabled)')){c.checked=true;c.dispatchEvent(new Event('change'));}input('task','Keep the meaning.');await click('Build context preview');check(JSON.parse(document.querySelector('[data-exact-payload]').textContent).messages[0].content===(await prompt()).baselineText,'Reopened preview includes effective baseline');}
  else{
   const baseline=await prompt();input('systemPrompt','Native author custom café 雪\nLiteral {{x}}');await pause('manual-save');await wait(async()=>(await prompt()).customized);check((await prompt()).effectiveText==='Native author custom café 雪\nLiteral {{x}}','Physical Save persists exact project prompt');
   await click('Restore baseline');check(!document.querySelector('.prompt-restore').hidden&&document.querySelector('.prompt-restore').textContent.includes(baseline.baselineText),'Restore shows current and installed baseline before confirmation');await click('Cancel restore');check((await prompt()).customized,'Cancel restore preserves override');
   await click('Restore baseline');await click('Confirm restore baseline');check(!(await prompt()).customized,'Confirmed restore removes override');await click('Undo project change');check((await prompt()).effectiveText==='Native author custom café 雪\nLiteral {{x}}','Undo restore retains exact custom text');await click('Redo project change');check(!(await prompt()).customized,'Redo restore reinstates baseline');
   input('systemPrompt','Draft protected across navigation');await click('Close settings');check(!!root()&&document.querySelector('[name="systemPrompt"]').value==='Draft protected across navigation','Close guard retains unsaved prompt');await click('Discard prompt changes');await click('Close settings');await open();check(document.querySelector('[name="systemPrompt"]').value===baseline.baselineText,'Settings reopen displays persisted baseline');
   await click('Context preparation');const choices=[...document.querySelectorAll('.context-references input')];check(choices.length===2,'Exact approved card and lore revisions available');for(const c of choices){c.checked=true;c.dispatchEvent(new Event('change'));}input('task','Keep the meaning.');await click('Build context preview');const body=document.querySelector('[data-exact-payload]').textContent;check(body.includes('Mara')&&body.includes('last tram')&&JSON.parse(body).messages[0].content===baseline.baselineText,'Complete payload includes exact approved card/lore and baseline');
   await click('Build context preview');check(document.querySelector('[data-exact-payload]').textContent===body,'Repeated preview is deterministic');input('contextBudget','256');await click('Build context preview','CONTEXT_BUDGET');check(!document.querySelector('[data-exact-payload]')&&choices.every(c=>c.checked)&&document.querySelector('[name="task"]').value==='Keep the meaning.','Budget refusal retains all author inputs without truncation');input('contextBudget','32768');
   const library=await read('references.list',payload());const card=library.document.cards[0];const fields=structuredClone(card.revisions.find(v=>v.id===card.approvedRevisionId).content);for(const key of Object.keys(fields))if(!['title','tags','scope','knowledgeNotes','provenance','citations','links','linkedCharacterId','aliases','description','appearanceNotes','personality','motivations','background','relationships','speakingStyle','exampleDialogue','linkedLoreIds'].includes(key))delete fields[key];fields.description+=' Explicit fixture update.';
   await call('references.apply',{...payload(),expectedRevision:library.revision,command:{type:'save',kind:'card',recordId:card.id,fields}});await click('Build context preview','STALE_CONTEXT');check(choices.every(c=>c.checked),'Stale selection is retained for explicit correction');await click('Reload saved choices');for(const c of document.querySelectorAll('.context-references input:not(:disabled)')){c.checked=true;c.dispatchEvent(new Event('change'));}await click('Build context preview');
   await click('System prompts');input('systemPrompt','External draft kept.');await pause('external-prompt');await click('Save prompt','STALE_CONTEXT');check(document.querySelector('[name="systemPrompt"]').value==='External draft kept.','External prompt edit refuses stale Save and retains draft');await click('Discard prompt changes');await click('Reload saved choices');check(!(await prompt()).customized,'Explicit reload retains externally extended baseline');
   await click('Close settings');
   for(const theme of ['light','dark']){document.querySelector('.shell-settings').click();await wait(()=>document.querySelector('#setting-theme'));const s=document.querySelector('#setting-theme');s.value=theme;s.dispatchEvent(new Event('change'));await wait(()=>document.documentElement.dataset.theme===theme);await click('Current project');await wait(()=>root()?.dataset.busy==='false');await click('Context preparation');for(const c of document.querySelectorAll('.context-references input:not(:disabled)')){c.checked=true;c.dispatchEvent(new Event('change'));}input('task','Keep the meaning.');await click('Build context preview');await pause('observe-'+theme);if(theme==='dark')await pause('observe-narrow');await click('Close settings');}
   await click('Close Project');await click('Source foundation fixture');await wait(()=>document.querySelector('.scene-workspace'));project=await read('project.current');await open();check((await prompt()).customized===false,'Project close/reopen retains baseline override removal');
  }
  const sourceAfter=await Promise.all(inventory.files.map(f=>read('source.open',{sessionId:project.sessionId,path:f.path})));check(JSON.stringify(sourceAfter.map(v=>v.text))===JSON.stringify(sourceBefore.map(v=>v.text)),'Prompt and context operations preserve every game source');details.stage='complete';details.passed=true;
 }catch(e){details.passed=false;details.errorCode=e.code??'PROBE_ASSERTION';details.failure=String(e).slice(0,200);}
 await call('probe.runtimeUiReport',details);
})();
