export interface PromptModel { revision:string; effectiveText:string; baselineText:string; baselineVersion:string; baselineDigest:string; savedBaselineVersion:string|null; savedBaselineDigest:string|null; customized:boolean; styleNotes:string; canUndo:boolean; canRedo:boolean }
export interface Target { sceneId:string; beatId:string; sourceRevision:string; label:string }
export interface Choice { kind:string; recordId:string; revisionId:string; number:number; title:string; linkedCharacterId?:string|null; eligible:boolean; issues:string[] }
export interface Options { prompt:PromptModel; targets:Target[]; structureRevision:string; references:Choice[]; referenceDiagnostic:string|null }
export type PromptCommand = {type:"save";text:string}|{type:"restore"|"undo"|"redo"};
export interface Selection { kind:string; recordId:string; revisionId:string }
export interface PreviewInput { expectedPromptRevision:string; expectedStructureRevision:string; sceneId:string; beatId:string; expectedSourceRevision:string; references:Selection[]; task:string; contextBudget:number; maximumResponse:number; contextCeiling:number }
export interface Preview { serializedPayload:string; payloadDigest:string; included:Selection[]; excluded:unknown[]; dependencies:unknown[]; exclusionPolicy:string[]; unrelatedDraftsExcluded:string[]; uncertainty:string; customCodeMarker:string; readSet:Record<string,string>; size:{serializedBytes:number; estimatedInputTokens:number; maximumResponse:number; margin:number; total:number; contextBudget:number; contextCeiling:number; estimator:string; componentBytes:Record<string,number>} }
export interface PromptActions { load():Promise<Options>; apply(command:PromptCommand,revision:string):Promise<PromptModel>; preview(input:PreviewInput):Promise<Preview>; current():boolean }
export interface PromptController { canLeave():boolean; dispose():void }
function el<K extends keyof HTMLElementTagNameMap>(tag:K,text="",cls=""):HTMLElementTagNameMap[K]{const n=document.createElement(tag);n.textContent=text;n.className=cls;return n;}
function errorMessage(e:unknown):string{return typeof(e as {message?:unknown})?.message==="string"?(e as Error).message:"The action failed. Your input has been kept.";}
export function mountPromptPreparation(host:HTMLElement,actions:PromptActions):PromptController{
 const root=el("div","","prompt-preparation");host.append(root);let model:Options|undefined,busy=false,disposed=false,sequence=0,tab="prompt",savedEditorText="";
 const active=():boolean=>!disposed&&actions.current()&&root.isConnected;
 const notice=el("p","Loading project prompts…","prompt-notice");notice.role="status";
 const tabs=el("div","","reference-tabs");tabs.role="tablist";tabs.ariaLabel="Project assistance";
 const editor=el("section");editor.role="tabpanel";editor.ariaLabel="System prompts";
 const context=el("section");context.role="tabpanel";context.ariaLabel="Context preparation";context.hidden=true;
 const prompt=el("textarea");prompt.rows=9;prompt.name="systemPrompt";prompt.ariaLabel="Dialogue rewrite system prompt";
 const info=el("p","","muted");const style=el("pre","","prompt-prose");style.ariaLabel="Project style notes";
 const restorePreview=el("div","","prompt-restore");restorePreview.hidden=true;
 const currentText=el("pre","","prompt-prose"),installedText=el("pre","","prompt-prose");
 const result=el("div","","context-preview");result.ariaLive="polite";
 const toolbar=el("div","","prompt-actions");
 const dirty=():boolean=>!!model&&prompt.value!==savedEditorText;
 const button=(label:string,fn:()=>void,parent:HTMLElement=toolbar):HTMLButtonElement=>{const b=el("button",label,"button");b.type="button";b.onclick=fn;parent.append(b);return b;};
 const invalidate=():void=>{result.replaceChildren();delete root.dataset.payloadDigest;delete root.dataset.previewOutcome;};
 const message=(text:string,error=false):void=>{notice.textContent=text;notice.dataset.kind=error?"error":"normal";};
 const state=():void=>{
  root.dataset.busy=String(busy);editor.toggleAttribute("data-unsubmitted",dirty());
  root.querySelectorAll<HTMLInputElement|HTMLTextAreaElement|HTMLSelectElement|HTMLButtonElement>("input,textarea,select,button").forEach(n=>n.disabled=busy||!model);
  if(!busy&&model){save.disabled=!dirty();discard.disabled=!dirty();restore.disabled=dirty()||!model.prompt.customized;undo.disabled=dirty()||!model.prompt.canUndo;redo.disabled=dirty()||!model.prompt.canRedo;build.disabled=dirty()||!targets.value;reload.disabled=dirty();for(const c of refs.querySelectorAll<HTMLInputElement>('input[data-ineligible="true"]'))c.disabled=true;}
 };
 const drawPrompt=():void=>{if(!model)return;prompt.value=model.prompt.effectiveText;savedEditorText=prompt.value;info.textContent=`Dialogue rewrite · This project · ${model.prompt.customized?"Customized":"Installed baseline"} · Installed baseline v${model.prompt.baselineVersion} (${model.prompt.baselineDigest})${model.prompt.customized?` · Saved against v${model.prompt.savedBaselineVersion} (${model.prompt.savedBaselineDigest})`:""}`;style.textContent=model.prompt.styleNotes||"No saved project style notes.";restorePreview.hidden=true;invalidate();state();};
 const save=button("Save prompt",()=>{void mutate({type:"save",text:prompt.value});});save.classList.add("primary");
 const discard=button("Discard prompt changes",()=>{if(busy||!model)return;drawPrompt();message("Returned to saved prompt.");});
 const restore=button("Restore baseline",()=>{if(busy||dirty()||!model)return;currentText.textContent=model.prompt.effectiveText;installedText.textContent=model.prompt.baselineText;restorePreview.hidden=false;confirm.focus();});
 const undo=button("Undo project change",()=>{void mutate({type:"undo"});});const redo=button("Redo project change",()=>{void mutate({type:"redo"});});
 editor.append(el("h3","System prompts"),el("p","Undo and Redo use the shared project history.","muted"),info,el("p","Edit the authoring instructions for Dialogue rewrite. Save explicitly to this project."),prompt,el("h4","Project style notes (saved separately)"),style,toolbar,restorePreview);
 restorePreview.append(el("h4","Restore Dialogue rewrite baseline?"),el("p","This removes only the saved override for this action. The change is saved immediately and can be undone."),el("h5","Current saved text"),currentText,el("h5","Installed baseline"),installedText);
 const confirm=button("Confirm restore baseline",()=>{void mutate({type:"restore"});},restorePreview);
 button("Cancel restore",()=>{restorePreview.hidden=true;restore.focus();},restorePreview);
 prompt.oninput=()=>{restorePreview.hidden=true;invalidate();state();message(dirty()?"Unsaved prompt changes. Save or discard before leaving or preparing context.":"Saved prompt.");};
 const controls=el("div","","context-controls");
 const label=(text:string,control:HTMLElement):void=>{const l=el("label");l.append(el("span",text),control);controls.append(l);};
 const targets=el("select");targets.ariaLabel="Saved dialogue target";label("Saved dialogue or narration",targets);
 const task=el("textarea");task.name="task";task.ariaLabel="Task instructions";task.rows=3;label("Task instructions (this preview)",task);
 const limits=el("div","","context-limits");const numbers:HTMLInputElement[]=[];
 for(const [name,text,value]of [["contextBudget","Total context budget (tokens)",32768],["maximumResponse","Maximum response reserve (tokens)",1024],["contextCeiling","Configured capacity (unverified tokens)",32768]]as const){const n=el("input");n.type="number";n.name=name;n.min="1";n.max="2000000";n.step="1";n.value=String(value);n.ariaLabel=text;const l=el("label");l.append(el("span",text),n);limits.append(l);numbers.push(n);}
 const refs=el("div","","context-references");refs.role="group";refs.ariaLabel="Exact approved reference revisions";
 const build=button("Build context preview",()=>{void preview();},context);build.classList.add("primary");
 const reload=button("Reload saved choices",()=>{void load();},context);
 context.prepend(el("h3","Prepare Dialogue rewrite context"),el("p","Inspect one saved Beat and explicitly selected reference revisions. This preparation does not send or apply anything."),controls,limits,el("p","These are explicit preview overrides. Saved provider/model limits are available under Application → AI providers; no profile is changed here.","muted"),refs);context.append(result);
 function choices():void{if(!model)return;targets.replaceChildren();for(const t of model.targets){const o=el("option",t.label);o.value=t.beatId;targets.append(o);}refs.replaceChildren(el("h4","Approved Character cards and lore"));if(model.referenceDiagnostic)refs.append(el("p",model.referenceDiagnostic,"error-message"));if(!model.references.length)refs.append(el("p","No approved revisions are available. Create cards or lore in the library first.","muted"));for(const r of model.references){const l=el("label","","reference-check"),check=el("input");check.type="checkbox";check.dataset.kind=r.kind;check.dataset.recordId=r.recordId;check.dataset.revisionId=r.revisionId;check.dataset.ineligible=String(!r.eligible);l.append(check,el("span",`${r.kind==="card"?"Character card":"Lore"}: ${r.title} · saved version ${r.number} · ${r.revisionId}${r.eligible?"":" · unavailable: stale or missing citations"}`));refs.append(l);check.onchange=()=>{invalidate();};}state();}
 for(const c of [targets,task,...numbers]){c.addEventListener(c===targets?"change":"input",()=>invalidate());}
 async function load():Promise<void>{if(busy||!active()||dirty())return;busy=true;state();try{const next=await actions.load();if(!active())return;model=next;drawPrompt();choices();message("Saved choices loaded. Select exact revisions before building a preview.");}catch(e){if(active())message(errorMessage(e),true);}finally{busy=false;if(active())state();}}
 async function mutate(command:PromptCommand):Promise<void>{if(busy||!active()||!model||(command.type!=="save"&&dirty()))return;busy=true;restorePreview.hidden=true;root.dataset.mutationOutcome="pending";state();invalidate();message("Saving…");try{const next=await actions.apply(command,model.prompt.revision);if(!active())return;model.prompt=next;root.dataset.mutationOutcome="committed";delete root.dataset.errorCode;drawPrompt();message("Saved. Build a fresh context preview.");prompt.focus();}catch(e){if(active()){root.dataset.mutationOutcome="refused";root.dataset.errorCode=(e as {code?:string}).code;message(errorMessage(e),true);}}finally{if(active()){root.dataset.mutationSequence=String(++sequence);busy=false;state();}}}
 async function preview():Promise<void>{if(busy||!active()||!model||dirty())return;const target=model.targets.find(t=>t.beatId===targets.value);if(!target)return;busy=true;state();invalidate();message("Preparing saved context…");try{const selected=[...refs.querySelectorAll<HTMLInputElement>('input:checked')].map(c=>({kind:c.dataset.kind!,recordId:c.dataset.recordId!,revisionId:c.dataset.revisionId!}));const input:PreviewInput={expectedPromptRevision:model.prompt.revision,expectedStructureRevision:model.structureRevision,...target,expectedSourceRevision:target.sourceRevision,references:selected,task:task.value,contextBudget:Number(numbers[0]!.value),maximumResponse:Number(numbers[1]!.value),contextCeiling:Number(numbers[2]!.value)}; // strip display-only target fields at typed IPC boundary
 const {sceneId,beatId,expectedSourceRevision,expectedPromptRevision,expectedStructureRevision,references,task:instructions,contextBudget,maximumResponse,contextCeiling}=input;
 const p=await actions.preview({sceneId,beatId,expectedSourceRevision,expectedPromptRevision,expectedStructureRevision,references,task:instructions,contextBudget,maximumResponse,contextCeiling});if(!active())return;
 root.dataset.payloadDigest=p.payloadDigest;root.dataset.previewOutcome="prepared";delete root.dataset.errorCode;
 const s=p.size;result.append(el("h4","Would-be payload · preview only"),el("p",`Input ${s.estimatedInputTokens.toLocaleString()} + response ${s.maximumResponse.toLocaleString()} + margin ${s.margin.toLocaleString()} = total ${s.total.toLocaleString()} / budget ${s.contextBudget.toLocaleString()} / capacity ${s.contextCeiling.toLocaleString()}`),el("p",`${s.serializedBytes.toLocaleString()} serialized UTF-8 bytes · ${s.estimator}`));
 const table=el("table");for(const [name,bytes]of Object.entries(s.componentBytes)){const row=el("tr");row.append(el("th",name),el("td",`${bytes.toLocaleString()} bytes`));table.append(row);}result.append(table,el("p","Component bytes describe content; serialized input also counts JSON escaping and message framing."));
 for(const [name,value]of [["Included exact revisions",p.included],["Excluded references",p.excluded],["Dependencies and link accounting",p.dependencies],["Other exclusions",p.exclusionPolicy],["Unrelated source drafts excluded",p.unrelatedDraftsExcluded],["Read revisions",p.readSet]]as const){const d=el("details");d.append(el("summary",name),el("pre",JSON.stringify(value,null,2),"prompt-prose"));result.append(d);}
 result.append(el("p",p.customCodeMarker),el("p",p.uncertainty),el("p",`Payload digest: ${p.payloadDigest}`));const body=el("pre",p.serializedPayload,"prompt-prose");body.dataset.exactPayload="true";result.append(el("h5","Complete serialized instructions and context"),body);message("Preview prepared. Changes require a fresh preview. No send is available.");
 }catch(e){if(active()){root.dataset.previewOutcome="refused";root.dataset.errorCode=(e as {code?:string}).code;message(errorMessage(e),true);}}finally{if(active()){root.dataset.previewSequence=String(++sequence);busy=false;state();}}}
 for(const [id,text,pane]of [["prompt","System prompts",editor],["context","Context preparation",context]]as const){const b=button(text,()=>{if(busy)return;tab=id;editor.hidden=tab!=="prompt";context.hidden=tab!=="context";for(const n of tabs.querySelectorAll<HTMLButtonElement>("button")){n.ariaSelected=String(n===b);n.tabIndex=n===b?0:-1;}pane.querySelector<HTMLElement>("textarea,select")?.focus();},tabs);b.role="tab";b.ariaSelected=String(id===tab);b.tabIndex=id===tab?0:-1;b.onkeydown=e=>{if(e.key==="ArrowLeft"||e.key==="ArrowRight"){e.preventDefault();[...tabs.querySelectorAll<HTMLButtonElement>("button")].find(n=>n!==b)?.click();}};}
 root.append(tabs,notice,editor,context);void load();
 return {canLeave:()=>{if(busy||dirty()){message(busy?"Wait for this action to finish.":"Save or discard the prompt changes before leaving.",true);if(!busy){editor.hidden=false;context.hidden=true;tabs.querySelectorAll<HTMLButtonElement>("button").forEach((b,i)=>b.ariaSelected=String(i===0));prompt.focus();}return false;}return true;},dispose:()=>{disposed=true;root.remove();}};
}
