import type { CoreOperation } from "./protocol.ts";
import type { Options } from "./prompt-ui.ts";
export interface RewriteActions {
  current(): boolean;
  inputState?(): {generation:number;blocked:boolean};
  call<T>(operation:CoreOperation,payload?:Record<string,unknown>):Promise<T>;
  accepted(sceneId:string,beatId:string):void;
}
interface Profile {profileId:string;credentialStatus:string;disabled:boolean;settings:{label:string;endpoint:string;model:string;contextBudget:number;contextCeiling:number;maximumResponse:number}}
interface Profiles {token:string;profiles:Profile[]}
interface Segment {literal?:string;token?:string}
interface Protected {token:string;originalSource:string}
interface Review {scene?:{id:string;sourcePath:string;displayName:string;chapterId:string};chapter?:unknown;action?:string; assignedBeatIds?:string[]; beats?:{type:string;characterId?:string;text:string}[];anchor?:unknown;terminal?:unknown;proposalId:string;previewDigest:string;target:{sceneId:string;beatId:string};beforeSegments:Segment[];segments:Segment[];protected:Protected[];patches:{path:string;before:string;after:string}[];uncertainty:string}
interface Prepared {chapter?:unknown;anchor?:unknown;terminal?:unknown;token:string;payloadDigest:string;serializedPayload:string;destination:{provider:string;endpoint:string;model:string;connectionLocation:string;inferenceLocality:string;retention:string};size:{serializedBytes:number;estimatedInputTokens:number;maximumResponse:number;margin:number;total:number;contextBudget:number;contextCeiling:number};context:{included:unknown[];excluded:unknown[];dependencies:unknown[];unrelatedDraftsExcluded:string[];exclusionPolicy:string[]};protected:Protected[];responseMode:string}
interface Status {requestId:string;done:boolean;state:string;message:string|null;proposal:Review|null}
function el<K extends keyof HTMLElementTagNameMap>(tag:K,text=""):HTMLElementTagNameMap[K]{const n=document.createElement(tag);n.textContent=text;return n;}
function prose(label:string,text:string):HTMLElement {const s=el("section");s.append(el("h4",label),el("pre",text));return s;}
export interface RewriteController { hasWork():boolean; busy():boolean; dispose():void }
/** Nonmodal, session-owned Assist. All model/source content is passive text. */
export function mountRewrite(host:HTMLElement,sceneId:string,beatId:string,actions:RewriteActions,action="rewriteDialogue"):RewriteController {
 const continuing=action==="continueScene",drafting=action==="draftScene";
 const actionTitle=drafting?"Draft Scene":continuing?"Continue Scene":"Rewrite dialogue";
 const panel=el("aside");panel.className="rewrite-panel";panel.ariaLabel=actionTitle;
 const title=el("h3",actionTitle),target=el("p","Loading saved target…"),status=el("p");status.role="status";status.ariaLive="polite";
 const fields=el("div");fields.className="rewrite-fields";
 const profile=el("select");profile.name="rewriteProfile";
 const task=el("textarea");task.name="rewriteTask";task.rows=4;task.maxLength=32768;
 const label=(text:string,c:HTMLElement):void=>{const l=el("label",text);l.className="field";l.append(c);fields.append(l);};
 const sceneTitle=el("input");sceneTitle.name="draftSceneTitle";sceneTitle.maxLength=160;
 if(drafting)label("Scene title",sceneTitle);
 label("Task",task);label("Studio profile",profile);
 const number=(name:string,text:string,min:number,max:number,defaultValue:string):HTMLInputElement=>{const i=el("input");i.type="number";i.name=name;i.min=String(min);i.max=String(max);i.step="1";i.value=defaultValue;label(text,i);return i;};
 const budget=number("rewriteBudget","Context budget (estimated tokens)",256,2000000,"32768"),reserve=number("rewriteResponse","Maximum response (tokens)",1,2000000,"1024"),capacity=number("rewriteCapacity","Configured server capacity (unverified tokens)",256,2000000,"32768"),timeout=number("rewriteTimeout","Response deadline (seconds)",30,1800,"600");
 const refs=el("fieldset");refs.className="rewrite-references";refs.append(el("legend","Include exact saved references"));
 const tools=el("div");tools.className="studio-actions";
 const button=(text:string):HTMLButtonElement=>{const b=el("button",text);b.className="button";tools.append(b);return b;};
 const reload=button("Reload saved choices"),prepare=button("Review complete send"),send=button("Generate proposal"),cancel=button("Cancel request"),accept=button(drafting?"Accept Scene":continuing?"Accept Beat group":"Accept 1 change"),discard=button("Discard proposal"),close=button("Close Assist");
 prepare.classList.add("primary");accept.classList.add("primary");
 const result=el("div");result.className="rewrite-result";
 panel.append(title,target,el("p",drafting?"Create one new Scene here with 1–8 dialogue/narration Beats and an explicit Return. Connecting it is a separate operation.":continuing?"Insert 1–8 new dialogue/narration Beats before this saved Beat. The existing terminal stays in place. Sending and accepting are separate actions.":"Replace one saved dialogue or narration Beat. Sending and accepting are separate actions."),fields,refs,tools,status,result);host.append(panel);
 let options:Options|undefined,profiles:Profiles|undefined,prepared:Prepared|undefined,review:Review|undefined,requestId:string|undefined,working=false,active=false,disposed=false,generation=0,consumed=false;
 let inputGeneration:number|undefined;
 const checkInput=(fresh=false):number=>{const input=actions.inputState?.()??{generation:0,blocked:false};if(input.blocked)throw Error("Finish or discard unsubmitted author input before continuing. Input retained.");if(!fresh&&inputGeneration!==input.generation)throw Error("Author input changed after preparation. Review a fresh send before continuing.");return input.generation;};
 let timer:ReturnType<typeof setTimeout>|undefined;let acceptSequence=0;
 const recordError=(e:unknown):void=>{panel.dataset.errorCode=typeof (e as {code?:unknown})?.code==="string"?(e as {code:string}).code:"ACTION_REFUSED";message(e instanceof Error?e.message:"The action was refused. Input retained.");};
 const current=():boolean=>!disposed&&actions.current()&&panel.isConnected;
 const message=(text:string):void=>{status.textContent=text;};
 const state=():void=>{panel.dataset.busy=String(working);panel.dataset.active=String(active);const p=profiles?.profiles.find(p=>p.profileId===profile.value);for(const c of panel.querySelectorAll<HTMLInputElement|HTMLTextAreaElement|HTMLSelectElement>("input,textarea,select"))c.disabled=working||active||c.dataset.ineligible==="true";reload.disabled=working||active;prepare.disabled=working||active||!options||!p||p.disabled||p.credentialStatus!=="configured"||!task.value.trim()||(drafting&&!sceneTitle.value.trim());send.disabled=working||active||!prepared||consumed;cancel.disabled=working||!active;accept.disabled=working||active||!review||consumed;discard.disabled=working||active||!review;close.disabled=working;};
 const invalidate=():void=>{delete panel.dataset.errorCode;prepared=undefined;review=undefined;consumed=false;result.replaceChildren();delete panel.dataset.payloadDigest;delete panel.dataset.previewDigest;message("Changes require a fresh send review.");state();};
 for(const control of [sceneTitle,task,budget,reserve,capacity,timeout])control.addEventListener("input",invalidate);
 const defaults=():void=>{const p=profiles?.profiles.find(p=>p.profileId===profile.value);if(p){budget.value=String(p.settings.contextBudget);capacity.value=String(p.settings.contextCeiling);reserve.value=String(p.settings.maximumResponse);}invalidate();};
 profile.addEventListener("change",defaults);
 const load=async():Promise<void>=>{if(working||active)return;working=true;state();const version=++generation;try{const o=await actions.call<Options>("context.options"),p=await actions.call<Profiles>("ai.profiles");if(!current()||version!==generation)return;options=drafting?{...o,prompt:o.draftPrompt!,targets:(o.chapters??[]).map(c=>({sceneId:c.id,beatId:"",sourceRevision:"",label:`Chapter · ${c.displayName}`}))}:continuing?{...o,prompt:o.continuePrompt!,targets:o.anchors??[]}:o;profiles=p;const t=options.targets.find(t=>t.sceneId===sceneId&&t.beatId===beatId);if(!t)throw Error("Saved target unavailable. Return to Story and select again.");target.textContent=t.label;if(continuing)target.append(el("pre",`Existing terminal (preserved): ${JSON.stringify(t.terminal)}`));profile.replaceChildren();for(const item of p.profiles){const choice=el("option",item.settings.label);choice.value=item.profileId;profile.append(choice);}refs.replaceChildren(el("legend","Include exact saved references"));for(const r of o.references){const l=el("label",`${r.kind} · ${r.title} · revision ${r.number}${r.eligible?"":" · unavailable"}`),check=el("input");check.type="checkbox";check.value=JSON.stringify({kind:r.kind,recordId:r.recordId,revisionId:r.revisionId});if(!r.eligible)check.dataset.ineligible="true";check.addEventListener("change",invalidate);l.prepend(check);refs.append(l);}defaults();message("Select references explicitly, enter a task, then review the complete send. Opening Assist sends nothing.");}catch(e){if(current())message(e instanceof Error?e.message:"Choices unavailable.");}finally{working=false;state();}};
 const showPrepared=(p:Prepared):void=>{result.replaceChildren();panel.dataset.payloadDigest=p.payloadDigest;const d=p.destination,s=p.size;result.append(el("h4","Review complete send"),el("p",`${d.provider} · ${d.endpoint} · exact model ${d.model} · ${d.connectionLocation} · inference locality ${d.inferenceLocality}`),el("p",d.retention),el("p",`${s.estimatedInputTokens} input estimate + ${s.maximumResponse} response reserve + ${s.margin} margin = ${s.total}; budget ${s.contextBudget}, unverified capacity ${s.contextCeiling}. UTF-8 byte estimate, not measured tokens. Request overrides do not change saved profiles.`),el("p",p.responseMode));result.append(prose("Included references, dependencies and exclusions",JSON.stringify(p.context,null,2)),prose(drafting?"Reviewed Chapter title and terminal":continuing?"Saved insertion anchor and terminal":"Preserved tokens",JSON.stringify(drafting?p.chapter:continuing?{anchor:p.anchor,terminal:p.terminal}:p.protected,null,2)),prose("Complete exact request body",p.serializedPayload),el("p",`Payload digest: ${p.payloadDigest}`));message("Inspect the destination and complete body. Generate proposal sends this review once.");};
 const semantic=(segments:Segment[],tokens:Protected[]):string=>segments.map(s=>s.literal??`⟦Preserved: ${tokens.find(p=>p.token===s.token)?.originalSource??"unknown"}⟧`).join("");
 const showReview=(r:Review):void=>{result.replaceChildren();panel.dataset.previewDigest=r.previewDigest;result.append(el("h4","Review changes"));if(continuing||drafting){if(drafting)result.append(prose("New Scene, Chapter, source path and explicit Return",JSON.stringify({scene:r.scene,chapter:r.chapter,terminal:r.terminal,incomingConnection:"None"},null,2)));result.append(prose("Whole Beat group (new text is literal)",(r.beats??[]).map((b,i)=>`${i+1}. ${b.type} · Beat ${r.assignedBeatIds?.[i]??"pending"}${b.characterId?` · Character ${b.characterId}`:""}: ${b.text}`).join("\n")),prose("Preserved insertion anchor and terminal",JSON.stringify({anchor:r.anchor,terminal:r.terminal},null,2)));}else{result.append(prose("Saved text",semantic(r.beforeSegments,r.protected)),prose("Proposed text (new text is literal)",semantic(r.segments,r.protected)),prose("Preserved source tokens",JSON.stringify(r.protected,null,2)));}result.append(el("p",r.uncertainty));for(const patch of r.patches){const details=el("details");details.append(el("summary",`Exact Source changes · ${patch.path}`),prose("Before",patch.before),prose("After",patch.after));result.append(details);}result.append(el("p",`Preview digest: ${r.previewDigest}`));message(drafting?"Proposal received. No source changed. Accept this whole Scene once, or discard it.":continuing?"Proposal received. No source changed. Accept this whole Beat group once, or discard it.":"Proposal received. No source changed. Accept this whole replacement once, or discard it.");};
 const display=(s:Status):void=>{requestId=s.requestId;active=!s.done;status.dataset.state=s.state;message(s.message??(s.done?"Response unavailable or expired; prepare again.":`${s.state}… Cancel remains available; server computation may continue.`));if(s.done){if(s.proposal&&s.state==="completed"){review=s.proposal;consumed=false;showReview(review);}else{review=undefined;consumed=true;}}state();};
 const poll=async(id:string,version:number):Promise<void>=>{if(!current()||generation!==version)return;try{const s=await actions.call<Status>("ai.requestStatus",{requestId:id});if(!current()||generation!==version)return;display(s);if(!s.done)timer=setTimeout(()=>void poll(id,version),250);}catch(e){if(current()&&generation===version){message(e instanceof Error?e.message:"Status unavailable. Cancel or retry status.");timer=setTimeout(()=>void poll(id,version),500);}}};
 reload.onclick=()=>void load();
 prepare.onclick=()=>void(async()=>{if(prepare.disabled||!options||!profiles)return;working=true;state();const version=++generation;prepared=undefined;review=undefined;result.replaceChildren();try{const captured=checkInput(true);const t=options.targets.find(t=>t.sceneId===sceneId&&t.beatId===beatId)!;const p=await actions.call<Prepared>("rewrite.prepare",{profileId:profile.value,expectedProfileToken:profiles.token,timeoutSeconds:Number(timeout.value),context:{action,expectedPromptRevision:options.prompt.revision,expectedStructureRevision:options.structureRevision,...(drafting?{chapterId:sceneId,displayName:sceneTitle.value}:{sceneId,beatId,expectedSourceRevision:t.sourceRevision}),references:[...refs.querySelectorAll<HTMLInputElement>("input:checked")].map(c=>JSON.parse(c.value) as unknown),task:task.value,contextBudget:Number(budget.value),contextCeiling:Number(capacity.value),maximumResponse:Number(reserve.value)}});if(checkInput(true)!==captured)throw Error("Author input changed during preparation. Review a fresh send.");if(current()&&generation===version){inputGeneration=captured;prepared=p;consumed=false;showPrepared(p);}}catch(e){if(current())recordError(e);}finally{working=false;state();}})();
 send.onclick=()=>void(async()=>{if(send.disabled||!prepared)return;working=true;consumed=true;state();const version=++generation;try{checkInput();const s=await actions.call<Status>("rewrite.send",{token:prepared.token,payloadDigest:prepared.payloadDigest});requestId=s.requestId;if(!current()||generation!==version){await actions.call("ai.cancelRequest",{requestId});return;}working=false;display(s);void poll(requestId,version);}catch(e){if(current())message(e instanceof Error?e.message:"Send refused. Prepare again.");}finally{working=false;state();}})();
 const stop=async():Promise<boolean>=>{if(!requestId)return true;++generation;clearTimeout(timer);working=true;state();try{const s=await actions.call<Status>("ai.cancelRequest",{requestId});active=!s.done;review=undefined;consumed=true;message(s.message??"Cancelled. Task retained; prepare again.");return s.done;}catch(e){message(e instanceof Error?e.message:"Cancellation cleanup incomplete.");return false;}finally{working=false;state();}};
 cancel.onclick=()=>void stop();
 accept.onclick=()=>void(async()=>{if(accept.disabled||!review)return;working=true;state();try{checkInput();await actions.call("rewrite.accept",{proposalId:review.proposalId,previewDigest:review.previewDigest});if(current()){consumed=true;panel.dataset.acceptOutcome="accepted";message("Accepted and saved as one change. Undo is available in Story.");actions.accepted(drafting?review.scene!.id:sceneId,drafting?review.assignedBeatIds![0]!:beatId);}}catch(e){if(current()){panel.dataset.acceptOutcome="refused";recordError(e);}}finally{panel.dataset.acceptSequence=String(++acceptSequence);working=false;state();}})();
 const clear=async():Promise<boolean>=>{working=true;state();try{await actions.call("rewrite.discard");invalidate();return true;}catch(e){message(e instanceof Error?e.message:"Discard unavailable.");return false;}finally{working=false;state();}};
 discard.onclick=()=>void clear();
 close.onclick=()=>void(async()=>{if(working)return;if((task.value.trim()||(drafting&&sceneTitle.value.trim())||review||active)&&!window.confirm("Discard this unfinished task/proposal and close Assist?"))return;if(active&&!await stop())return;if(await clear())controller.dispose();})();
 const controller:RewriteController={hasWork:()=>!disposed&&(!!task.value.trim()||(drafting&&!!sceneTitle.value.trim())||!!review||active),busy:()=>working||active,dispose:()=>{disposed=true;++generation;clearTimeout(timer);panel.remove();}};
 panel.addEventListener("keydown",e=>{if(e.key==="Escape"&&!working){e.preventDefault();close.click();}});
 state();void load();return controller;
}
