import assert from "node:assert/strict";
import test from "node:test";
import { Window } from "happy-dom";
import { mountPromptPreparation, type Options, type Preview, type PromptCommand, type PromptModel } from "../src/prompt-ui.ts";
const tick=async()=>{await new Promise(r=>setTimeout(r,0));};
function setup():Window {const w=new Window({url:"http://tauri.localhost"});Object.assign(globalThis,{window:w,document:w.document,HTMLElement:w.HTMLElement,HTMLInputElement:w.HTMLInputElement,HTMLTextAreaElement:w.HTMLTextAreaElement,HTMLSelectElement:w.HTMLSelectElement,Event:w.Event});document.body.innerHTML='<main></main>';return w;}
const model=():Options=>({prompt:{revision:"p1",effectiveText:"Saved custom",baselineText:"Installed baseline",baselineVersion:"2",baselineDigest:"digest2",savedBaselineVersion:"1",savedBaselineDigest:"digest1",customized:true,styleNotes:"Separate notes",canUndo:true,canRedo:false},targets:[{sceneId:"scene",beatId:"beat",sourceRevision:"source",label:"Opening · Beat 1"}],structureRevision:"structure",referenceDiagnostic:null,references:[{kind:"card",recordId:"card",revisionId:"r2",number:2,title:"Mara",eligible:true,issues:[]},{kind:"lore",recordId:"lore",revisionId:"r3",number:3,title:"Train",eligible:false,issues:["stale"]}]});
const click=(name:string):void=>{const b=[...document.querySelectorAll<HTMLButtonElement>("button")].find(b=>b.textContent===name)!;assert(b,`Missing ${name}`);b.click();};
const enter=(name:string,text:string):void=>{const n=document.querySelector<HTMLInputElement|HTMLTextAreaElement>(`[name="${name}"]`)!;n.value=text;n.dispatchEvent(new Event("input"));};
test("prompt controller explicit save, confirmed restore, held owner, stale refusal and draft protection",async()=>{
 const w=setup();let m=model(),active=true;const commands:PromptCommand[]=[];let resolve!:(p:PromptModel)=>void;let reject!:(e:Error)=>void;
 const controller=mountPromptPreparation(document.querySelector("main")!,{current:()=>active,load:async()=>m,preview:async()=>{throw Error("Unused");},apply:async(c,r)=>{assert.equal(r,"p1");commands.push(c);return new Promise((a,b)=>{resolve=a;reject=b;});}});await tick();
 enter("systemPrompt","Draft café 雪");assert.equal(controller.canLeave(),false);click("Context preparation");assert.equal([...document.querySelectorAll<HTMLButtonElement>("button")].find(b=>b.textContent==="Build context preview")!.disabled,true);
 click("System prompts");click("Save prompt");click("Save prompt");assert.equal(commands.length,1);reject(Object.assign(Error("Reload saved prompt"),{code:"STALE_CONTEXT"}));await tick();assert.equal(document.querySelector<HTMLTextAreaElement>('[name="systemPrompt"]')!.value,"Draft café 雪");assert.equal(controller.canLeave(),false);assert.equal(document.querySelector<HTMLElement>(".prompt-preparation")!.dataset.errorCode,"STALE_CONTEXT");
 click("Discard prompt changes");assert.equal(controller.canLeave(),true);click("Restore baseline");assert.equal(commands.length,1);assert.equal(document.querySelector<HTMLElement>(".prompt-restore")!.hidden,false);assert.match(document.querySelector(".prompt-restore")!.textContent!,/Installed baseline/);click("Cancel restore");assert.equal(commands.length,1);click("Restore baseline");click("Confirm restore baseline");assert.equal(commands[1]!.type,"restore");resolve({...m.prompt,customized:false,effectiveText:m.prompt.baselineText});await tick();assert.equal(document.querySelector<HTMLTextAreaElement>('[name="systemPrompt"]')!.value,"Installed baseline");assert.equal(controller.canLeave(),true);
 enter("systemPrompt","Stale project completion");click("Save prompt");active=false;resolve({...m.prompt,effectiveText:"Late completion"});await tick();assert.equal(document.querySelector<HTMLTextAreaElement>('[name="systemPrompt"]')!.value,"Stale project completion");controller.dispose();await w.happyDOM.close();
});
test("context exact revision selection, budget refusal retains all input, preview invalidates on changes",async()=>{
 const w=setup();let requests:unknown[]=[];let rejectPreview=true;
 const p:Preview={serializedPayload:'{"messages":[]}',payloadDigest:"body",included:[],excluded:[],dependencies:[],exclusionPolicy:["No assets"],unrelatedDraftsExcluded:[],uncertainty:"Unknown runtime state",customCodeMarker:"Custom code excluded",readSet:{"source":"rev"},size:{serializedBytes:15,estimatedInputTokens:15,maximumResponse:10,margin:256,total:281,contextBudget:32768,contextCeiling:32768,estimator:"Byte estimate",componentBytes:{story:4}}};
 const c=mountPromptPreparation(document.querySelector("main")!,{current:()=>true,load:async()=>model(),apply:async()=>model().prompt,preview:async input=>{requests.push(input);if(rejectPreview)throw Object.assign(Error("Total exceeds budget"),{code:"CONTEXT_BUDGET"});return p;}});await tick();click("Context preparation");const checks=[...document.querySelectorAll<HTMLInputElement>('.context-references input')];assert.equal(checks[1]!.disabled,true);checks[0]!.checked=true;checks[0]!.dispatchEvent(new Event("change"));enter("task","Exact task");click("Build context preview");await tick();assert.equal(document.querySelector<HTMLElement>(".prompt-preparation")!.dataset.errorCode,"CONTEXT_BUDGET");assert.equal(checks[0]!.checked,true);assert.equal(document.querySelector<HTMLTextAreaElement>('[name="task"]')!.value,"Exact task");assert.deepEqual((requests[0] as {references:unknown[]}).references,[{kind:"card",recordId:"card",revisionId:"r2"}]);assert(!("label" in (requests[0] as object)));rejectPreview=false;click("Build context preview");await tick();assert.equal(document.querySelector('[data-exact-payload]')!.textContent,p.serializedPayload);enter("contextBudget","12345");assert.equal(document.querySelector('[data-exact-payload]'),null);assert.equal(document.querySelector<HTMLElement>(".prompt-preparation")!.dataset.payloadDigest,undefined);c.dispose();await w.happyDOM.close();
});
