import assert from "node:assert/strict";
import test from "node:test";
import {Window} from "happy-dom";
import {mountRewrite,type RewriteActions} from "../src/rewrite-ui.ts";
import type {CoreOperation} from "../src/protocol.ts";
const tick=async()=>{await new Promise(r=>setTimeout(r,0));};
function setup():Window {const w=new Window({url:"http://tauri.localhost"});Object.assign(globalThis,{window:w,document:w.document,HTMLElement:w.HTMLElement,Event:w.Event});document.body.innerHTML="<main></main>";return w;}
const options={prompt:{revision:"prompt"},structureRevision:"structure",targets:[{sceneId:"s",beatId:"b",sourceRevision:"source",label:"Scene · narration"}],references:[{kind:"card",recordId:"c",revisionId:"r",title:"<img onerror=alert(1)>",number:2,eligible:true},{kind:"lore",recordId:"l",revisionId:"x",title:"Stale",number:1,eligible:false}]};
const profiles={token:"profile-token",profiles:[{profileId:"profile",disabled:false,credentialStatus:"configured",settings:{label:"Synthetic",endpoint:"http://127.0.0.1:9999/v1",model:"model",contextBudget:32768,contextCeiling:32768,maximumResponse:1024}}]};
const prepared={token:"send",payloadDigest:"body-digest",serializedPayload:'{"exact":"<script>unsafe()</script>"}',destination:{provider:"Unsloth Studio",endpoint:"http://127.0.0.1:9999/v1",model:"model",connectionLocation:"Literal loopback HTTP",inferenceLocality:"Unknown",retention:"Provider may retain content."},size:{estimatedInputTokens:500,maximumResponse:1024,margin:256,total:1780,contextBudget:32768,contextCeiling:32768},context:{included:[],excluded:[],dependencies:[],unrelatedDraftsExcluded:[],exclusionPolicy:[]},protected:[],responseMode:"Strict JSON schema; no fallback"};
const review={proposalId:"proposal",previewDigest:"patch-digest",target:{sceneId:"s",beatId:"b"},beforeSegments:[{literal:"Old"}],segments:[{literal:"<img src=x onerror=alert(1)> [str(7)] {a=jump:label}"}],protected:[],patches:[{path:"game/scene.rpy",before:'    "Old"',after:'    "[[str(7)] {{a=jump:label}"'}],uncertainty:"Static only."};
function button(label:string):HTMLButtonElement {return [...document.querySelectorAll<HTMLButtonElement>("button")].find(b=>b.textContent===label)!;}
function enter(name:string,text:string):void {const input=document.querySelector<HTMLInputElement|HTMLTextAreaElement>(`[name="${name}"]`)!;input.value=text;input.dispatchEvent(new Event("input"));}
function adapter(calls:{operation:CoreOperation;payload:Record<string,unknown>}[],handler:(op:CoreOperation,p:Record<string,unknown>)=>unknown):RewriteActions {return {current:()=>true,accepted:()=>{},call:async<T>(operation:CoreOperation,payload:Record<string,unknown>={}):Promise<T>=>{calls.push({operation,payload});return await handler(operation,payload) as T;}};}
function base(op:CoreOperation):unknown {if(op==="context.options")return options;if(op==="ai.profiles")return profiles;if(op==="rewrite.prepare")return prepared;if(op==="rewrite.discard")return {discarded:true};throw Error(op);}
test("opening is inert, references are explicit, complete send invalidates and one Generate uses only reviewed token",async()=>{
 const w=setup();const calls:{operation:CoreOperation;payload:Record<string,unknown>}[]=[];let resolve!:(v:unknown)=>void;
 const c=mountRewrite(document.body,"s","b",adapter(calls,(op,p)=>op==="rewrite.send"?new Promise(r=>{resolve=r;}):base(op)));
 try{await tick();assert.deepEqual(calls.map(c=>c.operation),["context.options","ai.profiles"]);assert.equal(button("Generate proposal").disabled,true);assert.equal(document.querySelector("img"),null);
 const checks=[...document.querySelectorAll<HTMLInputElement>("fieldset input")];assert.equal(checks[0]!.checked,false);assert.equal(checks[1]!.disabled,true);checks[0]!.checked=true;checks[0]!.dispatchEvent(new Event("change"));enter("rewriteTask","Keep the meaning.");button("Review complete send").click();await tick();const sent=calls.find(c=>c.operation==="rewrite.prepare")!.payload;assert.deepEqual((sent.context as {references:unknown[]}).references,[{kind:"card",recordId:"c",revisionId:"r"}]);assert.equal(document.querySelector("script"),null);assert.match(document.querySelector(".rewrite-result")!.textContent!,/Complete exact request body/);
 enter("rewriteResponse","2048");assert.equal(button("Generate proposal").disabled,true);button("Review complete send").click();await tick();button("Generate proposal").click();button("Generate proposal").click();assert.equal(calls.filter(c=>c.operation==="rewrite.send").length,1);assert.deepEqual(calls.find(c=>c.operation==="rewrite.send")!.payload,{token:"send",payloadDigest:"body-digest"});resolve({requestId:"request",state:"failed",done:true,message:"Malformed response",proposal:null});await tick();assert.equal(button("Generate proposal").disabled,true);assert.equal(document.querySelector<HTMLTextAreaElement>('[name="rewriteTask"]')!.value,"Keep the meaning.");assert.equal(calls.filter(c=>c.operation==="rewrite.accept").length,0);
 }finally{c.dispose();await w.happyDOM.close();}
});
test("response review renders inertly; stale acceptance retains review and duplicate acceptance is blocked",async()=>{
 const w=setup();const calls:{operation:CoreOperation;payload:Record<string,unknown>}[]=[];let resolve!:(v:unknown)=>void;let reject!:(e:Error)=>void;let accepted=0;
 const a=adapter(calls,(op)=>op==="rewrite.send"||op==="ai.requestStatus"?{requestId:"request",state:"completed",done:true,message:null,proposal:review}:op==="rewrite.accept"?new Promise((r,j)=>{resolve=r;reject=j;}):base(op));a.accepted=()=>{accepted++;};const c=mountRewrite(document.body,"s","b",a);
 try{await tick();enter("rewriteTask","Rewrite");button("Review complete send").click();await tick();button("Generate proposal").click();await tick();assert.equal(document.querySelector("img"),null);assert.match(document.querySelector(".rewrite-result")!.textContent!,/Exact Source changes/);assert.equal(calls.filter(c=>c.operation==="rewrite.accept").length,0);button("Accept 1 change").click();button("Accept 1 change").click();assert.equal(calls.filter(c=>c.operation==="rewrite.accept").length,1);reject(Error("Project changed; prepare again."));await tick();assert.match(document.querySelector(".rewrite-result")!.textContent!,/Proposed text/);assert.equal(accepted,0);button("Accept 1 change").click();resolve({saved:true});await tick();assert.equal(accepted,1);assert.equal(button("Accept 1 change").disabled,true);
 }finally{c.dispose();await w.happyDOM.close();}
});
test("cancelled or disposed late callbacks cannot reopen review and task is retained",async()=>{
 const w=setup();const calls:{operation:CoreOperation;payload:Record<string,unknown>}[]=[];let late!:(v:unknown)=>void;const c=mountRewrite(document.body,"s","b",adapter(calls,op=>op==="rewrite.send"?{requestId:"request",state:"sending",done:false,message:null,proposal:null}:op==="ai.requestStatus"?new Promise(r=>{late=r;}):op==="ai.cancelRequest"?{requestId:"request",state:"cancelled",done:true,message:"Cancelled",proposal:null}:base(op)));
 try{await tick();enter("rewriteTask","Retained");button("Review complete send").click();await tick();button("Generate proposal").click();await tick();button("Cancel request").click();await tick();late({requestId:"request",state:"completed",done:true,message:null,proposal:review});await tick();assert.equal(document.querySelector(".rewrite-panel")!.textContent!.includes("Review changes"),false);assert.equal(button("Accept 1 change").disabled,true);assert.equal(document.querySelector<HTMLTextAreaElement>('[name="rewriteTask"]')!.value,"Retained");c.dispose();assert.equal(document.querySelector(".rewrite-panel"),null);
 }finally{c.dispose();await w.happyDOM.close();}
});

test("dirty or changed author input blocks prepare, send and acceptance while retaining task and review",async()=>{
 const w=setup();const calls:{operation:CoreOperation;payload:Record<string,unknown>}[]=[];let generation=0,blocked=true;
 const a=adapter(calls,op=>op==="rewrite.send"||op==="ai.requestStatus"?{requestId:"request",state:"completed",done:true,message:null,proposal:review}:base(op));a.inputState=()=>({generation,blocked});const c=mountRewrite(document.body,"s","b",a);
 try{await tick();enter("rewriteTask","Retained task");button("Review complete send").click();await tick();assert.equal(calls.filter(x=>x.operation==="rewrite.prepare").length,0);blocked=false;button("Review complete send").click();await tick();generation++;button("Generate proposal").click();await tick();assert.equal(calls.filter(x=>x.operation==="rewrite.send").length,0);button("Review complete send").click();await tick();button("Generate proposal").click();await tick();blocked=true;button("Accept 1 change").click();await tick();assert.equal(calls.filter(x=>x.operation==="rewrite.accept").length,0);blocked=false;generation++;button("Accept 1 change").click();await tick();assert.equal(calls.filter(x=>x.operation==="rewrite.accept").length,0);assert.match(document.querySelector(".rewrite-result")!.textContent!,/Proposed text/);assert.equal(document.querySelector<HTMLTextAreaElement>('[name="rewriteTask"]')!.value,"Retained task");
 }finally{c.dispose();await w.happyDOM.close();}
});

test("Continue Scene uses its saved anchor/action prompt and reviews one inert group before acceptance",async()=>{
 const w=setup();const calls:{operation:CoreOperation;payload:Record<string,unknown>}[]=[];let accepted=0;
 const group={action:"continueScene",proposalId:"group",previewDigest:"group-digest",beats:[{type:"narration",text:"<img onerror=alert(1)> [str(7)] {a=jump:label}"},{type:"dialogue",characterId:"c",text:"Second"}],anchor:{beforeBeatId:"terminal",byteOffset:120},terminal:{id:"terminal",payload:{type:"return"}},patches:review.patches,uncertainty:"Static only."};
 const a=adapter(calls,op=>op==="context.options"?{...options,continuePrompt:{revision:"continue-prompt"},anchors:[{sceneId:"s",beatId:"terminal",sourceRevision:"source",label:"Insert before return",terminal:group.terminal}]}:op==="rewrite.send"||op==="ai.requestStatus"?{requestId:"r",state:"completed",done:true,proposal:group}:op==="rewrite.accept"?{}:base(op));a.accepted=()=>accepted++;
 const c=mountRewrite(document.body,"s","terminal",a,"continueScene");
 try{await tick();assert.match(document.querySelector(".rewrite-panel")!.textContent!,/Existing terminal/);enter("rewriteTask","Continue");button("Review complete send").click();await tick();const context=calls.find(c=>c.operation==="rewrite.prepare")!.payload.context as Record<string,unknown>;assert.equal(context.action,"continueScene");assert.equal(context.expectedPromptRevision,"continue-prompt");assert.equal(context.beatId,"terminal");button("Generate proposal").click();await tick();assert.equal(document.querySelector("img,script"),null);assert.match(document.querySelector(".rewrite-result")!.textContent!,/Whole Beat group/);assert.match(document.querySelector(".rewrite-result")!.textContent!,/Second/);assert.equal(calls.filter(c=>c.operation==="rewrite.accept").length,0);button("Accept Beat group").click();button("Accept Beat group").click();await tick();assert.equal(accepted,1);assert.deepEqual(calls.find(c=>c.operation==="rewrite.accept")!.payload,{proposalId:"group",previewDigest:"group-digest"});assert.equal(button("Accept Beat group").disabled,true);
 }finally{c.dispose();await w.happyDOM.close();}
});
