import type { CoreOperation, CoreResponse } from '../src/protocol.ts';
const revision='a'.repeat(64);
const project={sessionId:'visual-session',projectId:'visual-project',title:'The Last Tram',folderName:'the-last-tram',chapterId:'chapter',chapterName:'Chapter One',sceneId:'apartment',sceneName:'The Apartment',sdkVersion:'8.5.3',resolution:{width:1920,height:1080}};
const source={path:'game/scenes/apartment.rpy',statement:'definition',sourceRevision:revision};
const characters=['Bec','Alice','Liv','Henry'].map((name,i)=>({id:name.toLowerCase(),technicalName:name.toLowerCase(),displayName:name,dialogueColor:'#B78461',defaultAppearanceId:i===3?undefined:`${name.toLowerCase()}-neutral`,source}));
const assets=[['apartment','Apartment at night','background'],['street','City street','background'],['cafe','Campus café','background'],['bec-neutral','Bec · neutral','characterAppearance'],['theme','Evening ambience','music']].map(([id,name,kind])=>({id:id!,displayName:name!,kind:kind!,relativePath:`game/images/${id}.png`,discoveryName:`bg ${id}`,sha256:revision,byteCount:12000,status:'available'}));
const authoring={schemaVersion:1,projectId:project.projectId,characters,assets,appearances:[{id:'bec-neutral',characterId:'bec',label:'Neutral',attributes:{outfit:'casual',pose:'neutral'},renderMode:'image',assetId:'bec-neutral'}],variables:[{id:'went-out',technicalName:'went_out',variableType:'bool',defaultValue:false,source},{id:'day',technicalName:'day',variableType:'int',defaultValue:'1',source},{id:'player-name',technicalName:'player_name',variableType:'string',defaultValue:'Alex',source}]};
const scenes=[['prologue','Prologue'],['apartment','The Apartment'],['stay-in','Stay in'],['outside','Head outside'],['new-day','A new day']].map(([id,name])=>({id:id!,chapterId:'chapter',displayName:name!,technicalLabel:id!.replaceAll('-','_'),sourcePath:`game/scenes/${id}.rpy`,sourceRevision:revision,sourceConflict:false,partial:false,beats:id==='apartment'?[{id:'background',byteStart:20,byteEnd:40,protected:false,payload:{type:'background',assetId:'apartment',transition:'none'}},{id:'show',byteStart:40,byteEnd:60,protected:false,payload:{type:'showCharacter',characterId:'bec',appearanceId:'bec-neutral',placement:'centre',transition:'none'}},{id:'dialogue',byteStart:60,byteEnd:80,protected:false,payload:{type:'dialogue',characterId:'bec',text:'Another long day…'}},{id:'choice',byteStart:80,byteEnd:110,protected:false,payload:{type:'choice',options:[{text:'Stay in and read',destinationSceneId:'stay-in'},{text:'Go for a walk',destinationSceneId:'outside'}]}},{id:'set',byteStart:110,byteEnd:125,protected:false,payload:{type:'setVariable',variableId:'went-out',value:false}}]:[]}));
const sceneModel={projectRevision:revision,sourceMapRevision:revision,entrySceneId:'prologue',lastOpen:{chapterId:'chapter',sceneId:'apartment'},chapters:[{id:'chapter',displayName:'Chapter One',directory:'game/scenes'}],scenes,authoring,canUndo:false,canRedo:false};
const accepted='label apartment:\n    scene bg apartment\n    show bec neutral at center\n    bec "Another long day…"\n    menu:\n        "Stay in and read":\n            jump stay_in\n        "Go for a walk":\n            jump outside\n';
let document={path:source.path,text:accepted,state:'clean',editable:true,dirty:false,baseRevision:revision,liveRevision:revision,draftVersion:0,hasBom:false,newline:'LF',partial:false,diagnostics:[],ranges:[],selectionStart:0,selectionEnd:0,canApplyBoth:false};
export async function visualRequest<T>(operation:CoreOperation,payload:Readonly<Record<string,unknown>>={}):Promise<CoreResponse<T>>{
 let value:unknown={};
 switch(operation){
 case 'project.listRecent':value=[{id:'tram',projectId:'visual-project',title:'The Last Tram',displayPath:'Documents / Stories / The Last Tram',lastOpenedUnixMs:Date.UTC(2026,8,29),status:'available'}];break;
 case 'project.openRecent':case 'project.current':value=project;break;
 case 'project.status':case 'project.flush':value='saved';break;
 case 'authoring.list':value=authoring;break;
 case 'character.create':{
  if(!/^[a-z][a-z0-9_]{0,63}$/.test(String(payload.technicalName))||!/^#[0-9a-f]{6}$/i.test(String(payload.dialogueColor)))return {protocolVersion:1,requestId:'visual',ok:false,error:{code:'INVALID_PAYLOAD',message:'Invalid technical name or colour'}};
  if(characters.some(c=>c.technicalName===payload.technicalName))return {protocolVersion:1,requestId:'visual',ok:false,error:{code:'SYMBOL_COLLISION',message:'That technical name is already used.'}};
  characters.push({id:String(payload.technicalName),technicalName:String(payload.technicalName),displayName:String(payload.displayName),dialogueColor:String(payload.dialogueColor),defaultAppearanceId:undefined,source:{path:'game/definitions/characters.rpy',statement:`define ${String(payload.technicalName)} = Character(${JSON.stringify(payload.displayName)}, color=${JSON.stringify(payload.dialogueColor)})`,sourceRevision:revision}});value=authoring;break;
 }
 case 'scene.list':value=sceneModel;break;
 case 'scene.apply':{const command=payload.command as {type:string;sceneId?:string;beatId?:string;beat?:unknown};if(command.type==='selectScene')sceneModel.lastOpen.sceneId=command.sceneId!;value=sceneModel;break;}
 case 'source.list':value={files:[{path:source.path,state:document.state,dirty:document.dirty,readOnly:false}],dirtyCount:Number(document.dirty),draftBytes:document.dirty?document.text.length:0};break;
 case 'source.open':value=payload.path==='game/definitions/characters.rpy'?{...document,path:payload.path,text:characters.map(c=>c.source.statement).join('\n')}:document;break;
 case 'source.updateDraft':document={...document,...payload,text:String(payload.text),dirty:payload.text!==accepted,state:payload.text!==accepted?'dirty':'clean',draftVersion:document.draftVersion+1};value=document;break;
 case 'source.save':document={...document,dirty:false,state:'clean'};value=document;break;
 case 'flow.list':value={observation:{status:'savedEdits',fromCache:false,checkedAt:Date.now()},revision,entrySceneId:'prologue',nodes:scenes.map(s=>({sceneId:s.id,name:s.displayName,label:s.technicalLabel,location:{path:s.sourcePath,revision,byteStart:0,byteEnd:20},partial:false,stale:false})),edges:[['prologue','apartment',''],['apartment','stay-in','Stay in and read'],['apartment','outside','Go for a walk'],['stay-in','new-day',''],['outside','new-day','']].map(([from,to,text],i)=>({id:`edge-${i}`,sceneId:from,beatId:'choice',optionOrdinal:i,text,kind:'choice',location:{path:source.path,revision,byteStart:80,byteEnd:110},destination:{kind:'resolved',sceneId:to},editable:true})),partial:false,stale:false,overLimit:false,notice:'Known saved paths'};break;
 case 'media.present':{const svg='<svg xmlns="http://www.w3.org/2000/svg" width="800" height="450"><rect width="800" height="450" fill="#32414b"/><circle cx="620" cy="100" r="45" fill="#deb688"/><path d="M0 350 190 160 410 360 620 230 800 350V450H0Z" fill="#526559"/><path d="M0 420 290 300 510 430 800 325V450H0Z" fill="#263b34"/></svg>';value={assetId:payload.assetId,purpose:payload.purpose,mimeType:'image/svg+xml',dataBase64:btoa(svg),sha256:revision,byteCount:svg.length,width:800,height:450,cacheKey:`${payload.assetId}:${revision}`};break;}
 }
 return {protocolVersion:1,requestId:'visual',ok:true,value:value as T};
}
