import copy
import importlib.util
import json
from pathlib import Path
import unittest
import tempfile
import time
from unittest.mock import patch

spec = importlib.util.spec_from_file_location("windows_probe", Path(__file__).with_name("windows-studio-credentials.py"))
probe = importlib.util.module_from_spec(spec)
spec.loader.exec_module(probe)

class WindowsFixtureGate(unittest.TestCase):
    def test_permission_absent_from_actual_tree_and_both_manifests_still_refuses(self):
        broken=probe.source_inputs();broken.pop("src-tauri/permissions/autogenerated/core_request.toml")
        with patch.object(probe,"source_inputs",return_value=broken):
            self.assertFalse(probe.package_inputs_match(broken,broken))

    def test_fault_receipt_collision_refuses_before_native_inspection_or_profile_mutation(self):
        with tempfile.TemporaryDirectory() as directory:
            out=Path(directory);root=out/"root";root.mkdir()
            profiles=root/"ai-profiles.json";profiles.write_bytes(b"retained profile bytes")
            probe.write(out/"run-6-launch.json",{"deadlineUnix":time.time()+30,"pid":123})
            probe.write(root/".studio-windows-step.json",{"phase":"1","step":"alpha-entry"})
            with patch.object(probe,"ACCEPTANCE",True),patch.object(probe,"OUTPUT",out),patch.object(probe,"root_from_state",return_value=root),patch.object(probe.ctypes,"WinDLL",side_effect=AssertionError("No native inspection")):
                for action,suffix in [("corrupt","fault.json"),("corrupt","restored.json"),("restore","restored.json")]:
                    receipt=out/("run-6-alpha-"+suffix);receipt.write_bytes(b"retained receipt")
                    with self.subTest(action=action,suffix=suffix),self.assertRaises(ValueError):probe.fault(action,"alpha")
                    self.assertEqual(profiles.read_bytes(),b"retained profile bytes")
                    self.assertEqual(receipt.read_bytes(),b"retained receipt")
                    self.assertFalse((out/"run-6-alpha-before.bin").exists())
                    receipt.unlink()

    def test_complete_installed_generated_toolchain_gate_and_missing_permissions_fail_closed(self):
        keys=["nodeInstalled","cargoInstalled","resolved","tools","windows","machine","environmentDigest","msvc","sdk","commit","diffDigest","generatedBefore"]
        built={key:{"recorded":"bytes"} for key in keys};built["sources"]=probe.source_inputs()
        self.assertTrue(probe.complete_inputs_match(built,built))
        for key in keys:
            changed=copy.deepcopy(built);changed[key]={"changed":True}
            with self.subTest(key=key):self.assertFalse(probe.complete_inputs_match(built,changed))
            del changed[key];self.assertFalse(probe.complete_inputs_match(changed,changed))
        broken=probe.source_inputs();broken.pop("src-tauri/permissions/autogenerated/core_request.toml")
        with patch.object(probe,"source_inputs",return_value=broken),patch.object(probe.subprocess,"run",side_effect=AssertionError("No dispatch")):
            with self.assertRaises(ValueError):probe.qualification_inputs()

    def test_reload_capture_acknowledgement_requires_live_exact_phase_bytes_status_and_owned_capture(self):
        with tempfile.TemporaryDirectory() as directory:
            out=Path(directory);root=out/"root";root.mkdir()
            probe.write(out/"run-7-launch.json",{"startedMonotonic":time.monotonic()-5,"pid":123})
            probe.write(root/".studio-windows-step.json",{"phase":"2","step":"beta-reload-required"})
            snapshot=root/".studio-windows-2-beta-reload-required.json";snapshot.write_bytes(b"unit-only synthetic persisted store")
            capture=out/"run-7-reload.png";capture.write_bytes(b"unit-only capture identity")
            value={"run":7,"phase":2,"saveStatus":probe.read(probe.RELOAD)["expectedResponse"]["saveStatus"],"controlsDisabled":True,"retryEnabled":True,
                   "profilesSha256":probe.sha(snapshot),"startSeconds":1,"endSeconds":2,"captures":[{"file":capture.name,"sha256":probe.sha(capture),"bytes":capture.stat().st_size}]}
            with patch.object(probe,"ACCEPTANCE",True),patch.object(probe,"OUTPUT",out),patch.object(probe,"root_from_state",return_value=root),patch.object(probe,"pid_absent",return_value=False):
                for change in [{"phase":1},{"controlsDisabled":False},{"retryEnabled":False},{"profilesSha256":"wrong"},{"endSeconds":301},{"captures":[]}]:
                    probe.write(out/"run-7-reload-observed.json",dict(value,**change))
                    with self.subTest(change=change),self.assertRaises(ValueError):probe.confirm_reload()
                    self.assertFalse((root/".studio-windows-reload-observed.json").exists())
                probe.write(out/"run-7-reload-observed.json",value);probe.confirm_reload()
                self.assertEqual(probe.read(root/".studio-windows-reload-observed.json"),{"run":7,"phase":2,"observed":True})
                with self.assertRaises(FileExistsError):probe.confirm_reload()

    def test_acceptance_ids_reject_old_phase_partial_resume_and_missing_build_without_dispatch(self):
        with patch.object(probe, "ACCEPTANCE", True):
            self.assertEqual(probe.run_prefix(6, 1), "run-6")
            self.assertEqual(probe.run_prefix(7, 2), "run-7")
            for run, phase in [(6,2),(7,1),(5,1),(4,2)]:
                with self.assertRaises(ValueError): probe.run_prefix(run,phase)
            with patch.object(probe, "qualification_inputs", side_effect=AssertionError("No inventory/dispatch")):
                for number in [None,1,2,4]:
                    with self.assertRaises(ValueError): probe.build(number)

    def test_equal_incomplete_manifest_missing_permission_optional_presence_or_fixture_refuses(self):
        inventory=probe.source_inputs()
        for key in ["src-tauri/permissions/core-request.toml", "$presence/public", "$presence/.cargo", "$presence/../.cargo",
                    "tests/fixtures/windows-studio-credential-reload-failure.json"]:
            broken=dict(inventory); del broken[key]
            with self.subTest(key=key): self.assertFalse(probe.package_inputs_match(broken,broken))
        changed=dict(inventory);changed["$presence/public"]="other"
        self.assertFalse(probe.package_inputs_match(inventory,changed))

    def test_reservation_refuses_each_receipt_or_package_collision_without_overwriting(self):
        with tempfile.TemporaryDirectory() as directory:
            root=Path(directory)
            paths=[root/name for name in ["attempt.json","launch.json","terminal.json","stdout.log","package"]]
            probe.reserve(paths)
            for path in paths:
                path.write_bytes(b"retained failure")
                with self.assertRaises(ValueError): probe.reserve(paths)
                self.assertEqual(path.read_bytes(),b"retained failure")
                path.unlink()

    def test_full_prior_phase_requires_run6_package_exit_pid_and_every_original_marker(self):
        report={"passed":True,"cleanupComplete":True,"evidence":"runtime-ui-packaged","case":"studio-settings",
                "details":{"passed":True,"stage":"complete","phase":1,"checks":probe.CHECKS[1]}}
        requests=[{"method":"GET","path":"/v1/models","label":"alpha","accepted":True}]*2
        value={"run":6,"passed":True,"stopped":True,"pidAbsent":True,"packageSha256":"candidate","elapsedSeconds":150,"exitCode":0,"report":report,"requests":requests}
        probe.validate_prior(value,"candidate")
        for change in [{"run":3},{"passed":False},{"pidAbsent":False},{"stopped":False},{"elapsedSeconds":301},{"packageSha256":"old"},{"exitCode":1},{"requests":[]}]:
            with self.subTest(change=change),self.assertRaises(ValueError): probe.validate_prior(dict(value,**change),"candidate")

    def test_combined_phase_requires_exact_reload_response_and_all_original_checks(self):
        report={"passed":True,"cleanupComplete":True,"evidence":"runtime-ui-packaged","case":"studio-settings",
                "details":{"passed":True,"stage":"complete","phase":2,"checks":probe.CHECKS[2]+probe.RELOAD_CHECKS,"reloadResponse":probe.read(probe.RELOAD)["expectedResponse"]}}
        requests=[{"method":"GET","path":"/v1/models","label":label,"accepted":True} for label in ["alpha","beta"]]
        probe.check_report(2,report,requests,0,reload=True)
        for defect in ["missing-marker","missing-original","wrong-pending","extra-get"]:
            value=copy.deepcopy(report); sent=copy.deepcopy(requests)
            if defect=="missing-marker":value["details"]["checks"].pop()
            elif defect=="missing-original":value["details"]["checks"].remove("Replacement preserved B and retired only owned A")
            elif defect=="wrong-pending":value["details"]["reloadResponse"]["cleanupPending"]=False
            else:sent.append(sent[0])
            with self.subTest(defect=defect),self.assertRaises(ValueError):probe.check_report(2,value,sent,0,reload=True)

    def test_final_store_rejects_wrong_revision_generation_foreign_unknown_and_surviving_profile(self):
        beta=probe.read(probe.FIXTURE);beta["revision"]=8
        final=copy.deepcopy(beta);final["revision"]=14;final["profiles"]=[]
        probe.validate_removed(beta,final)
        for defect in ["revision","activeDevelopmentGeneration","developmentGenerations","cleanup","unknown","profile"]:
            changed=copy.deepcopy(final)
            if defect=="revision":changed[defect]+=1
            elif defect in ["cleanup","developmentGenerations"]:changed[defect]=[]
            elif defect=="activeDevelopmentGeneration":changed[defect]=None
            elif defect=="unknown":changed[defect]=True
            else:changed["profiles"]=[beta["profiles"][1]]
            with self.subTest(defect=defect),self.assertRaises(ValueError):probe.validate_removed(beta,changed)

    def test_native_observations_require_order_retained_fields_ui_and_cumulative_entry_deadline(self):
        names=["alpha-entry","alpha-refusal","alpha-retry","gamma-entry","gamma-confirmation","cancel-entry","stale-refusal","cancel","get-alpha-1","get-alpha-2","exit"]
        evidence={"phase":1,"run":6,"events":[{"name":name,"startSeconds":i*2,"endSeconds":i*2+1,"passed":True,**({"requestSeconds":0.9,"cleanupSeconds":0.1} if name.startswith("get-") else {})} for i,name in enumerate(names)],
                  "observed":dict.fromkeys(["maskedNativeField","failedSaveRetainedInput","retryWithoutRetyping","staleSaveRetainedInput","cancelAfterExactRestore"],True)}
        probe.validate_observations(1,evidence)
        for defect in ["missing","order","deadline","retained","failed","entry-total"]:
            changed=copy.deepcopy(evidence)
            if defect=="missing":changed["events"].pop()
            elif defect=="order":changed["events"].reverse()
            elif defect=="deadline":changed["events"][-1]["endSeconds"]=301
            elif defect=="retained":changed["observed"]["failedSaveRetainedInput"]=False
            elif defect=="failed":changed["events"][0]["passed"]=False
            else:
                for event in changed["events"][1:]:event["startSeconds"]+=120;event["endSeconds"]+=120
            with self.subTest(defect=defect),self.assertRaises(ValueError):probe.validate_observations(1,changed)
        for elapsed in [0,-1,301,float("nan")]:
            with self.assertRaises(ValueError):probe.validate_elapsed(elapsed,300)

    def test_missing_or_out_of_budget_build_selection_refuses_before_preparation(self):
        with patch.object(probe, "source_inputs", side_effect=AssertionError("Must not prepare a build")):
            for number in [None, 0, 3]:
                with self.subTest(number=number), self.assertRaises(ValueError):
                    probe.build(number)

    def test_targeted_cancel_requires_failed_save_observation_exact_snapshot_and_zero_gets(self):
        status = "Credential entry cancelled; saved profile unchanged."
        report = {"passed":False,"cleanupComplete":True,"evidence":"runtime-ui-packaged","case":"studio-settings","details":{"passed":False,"phase":1,"stage":"alpha-entry",
                  "nativeStatus":status,"error":"Error: Native entry result: "+status,
                  "checks":["Fixed Windows phase selected","Shared v2 profiles and foreign cleanup retained","Initial fixture has no native keys"]}}
        observed={"failedSaveRetainedInput":True,"cancelAfterExactRestore":True}
        probe.check_cancel_report(report,[],1,b"fixture",b"fixture",observed)
        for failure in ["save-pass","exit","get","snapshot","observation","checks","status"]:
            value=copy.deepcopy(report); requests=[]; code=1; after=b"fixture"; evidence=dict(observed)
            if failure=="save-pass": value["passed"]=True
            elif failure=="exit": code=0
            elif failure=="get": requests=[{}]
            elif failure=="snapshot": after=b"changed"
            elif failure=="observation": evidence["failedSaveRetainedInput"]=False
            elif failure=="checks": value["details"]["checks"]=[]
            elif failure=="status": value["details"]["nativeStatus"]="API key saved"
            with self.subTest(failure=failure), self.assertRaises(ValueError):
                probe.check_cancel_report(value,requests,code,b"fixture",after,evidence)

    def test_partial_reopen_never_accepts_failed_flow_as_cancel_proof(self):
        alpha = copy.deepcopy(probe.read(probe.FIXTURE))
        alpha["revision"] += 2
        alpha["profiles"][0]["revision"] = 2
        alpha["profiles"][0]["credential"] = {"credentialId":"eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeee", "origin":"http://127.0.0.1:46082", "revision":1}
        gamma = copy.deepcopy(alpha)
        gamma["revision"] += 2
        gamma["profiles"][1]["revision"] = 2
        gamma["profiles"][1]["credential"] = {"credentialId":"ffffffff-ffff-4fff-8fff-ffffffffffff", "origin":"http://127.0.0.1:46082", "revision":1}
        receipt = {"run":3,"passed":False,"exitCode":1,"stopped":True,"elapsedSeconds":245,"requests":[],
                   "report":{"passed":False,"cleanupComplete":True,"evidence":"runtime-ui-packaged","case":"studio-settings","details":{"passed":False,"phase":1,"stage":"cancel-entry","error":"Error: Timeout: cancel-entry",
                   "checks":["Fixed Windows phase selected","Shared v2 profiles and foreign cleanup retained","Initial fixture has no native keys","Retained-field Retry saved A while foreign cleanup remained pending"]}}}
        probe.validate_partial_entry(receipt,alpha,gamma)
        for change in [{"passed":True},{"stopped":False},{"requests":[{}]},{"elapsedSeconds":301},{"run":2}]:
            with self.subTest(change=change), self.assertRaises(ValueError):
                probe.validate_partial_entry(dict(receipt,**change),alpha,gamma)
        for failure in ["inner-pass", "missing-check", "extra-check", "wrong-envelope"]:
            value = copy.deepcopy(receipt)
            if failure == "inner-pass": value["report"]["passed"] = True
            elif failure == "missing-check": value["report"]["details"]["checks"].pop()
            elif failure == "extra-check": value["report"]["details"]["checks"].append("unproved")
            elif failure == "wrong-envelope": value["report"]["case"] = "unrelated"
            with self.subTest(failure=failure), self.assertRaises(ValueError):
                probe.validate_partial_entry(value,alpha,gamma)
        missing = copy.deepcopy(gamma); missing["profiles"][1]["credential"] = None
        with self.assertRaises(ValueError): probe.validate_partial_entry(receipt,alpha,missing)

    def test_reuse_allows_only_external_controller_change_and_rejects_runtime_change(self):
        built = probe.source_inputs()
        built["scripts/windows-studio-credentials.py"] = "old-controller"
        current = dict(built, **{"scripts/windows-studio-credentials.py": "new-controller"})
        self.assertTrue(probe.package_inputs_match(built, current))
        for key in ["src-tauri/src/ai_native/windows.rs", "src-tauri/src/windows_studio_probe.js", "Cargo.lock",
                    "package.json", "index.html", "vite.config.ts", "tsconfig.json", "rust-toolchain.toml"]:
            changed = dict(current)
            changed[key] = "changed"
            with self.subTest(key=key):
                self.assertFalse(probe.package_inputs_match(built, changed))
            missing = dict(built)
            del missing[key]
            self.assertFalse(probe.package_inputs_match(missing, current))
        self.assertFalse(probe.package_inputs_match({}, {}))
        self.assertEqual(probe.run_prefix(3, 1), "phase-1-final")
        self.assertEqual(probe.run_prefix(4, 2), "phase-2")
        with self.assertRaises(ValueError):
            probe.run_prefix(4, 1)

    def test_saved_native_gate_rejects_missing_foreign_unowned_and_changed_other_profile(self):
        old = probe.read(probe.FIXTURE)
        saved = copy.deepcopy(old)
        saved["revision"] += 2
        saved["profiles"][0]["revision"] += 1
        saved["profiles"][0]["credential"] = {"credentialId":"eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeee", "origin":"http://127.0.0.1:46082", "revision":1}
        probe.validate_saved(old, saved, probe.A)
        for failure in ["missing", "file", "origin", "revision", "service", "uuid", "cleanup", "other",
                        "extra-profile", "duplicate-profile", "reorder", "store-revision", "unknown", "profile-unknown", "credential-unknown"]:
            value = copy.deepcopy(saved)
            c = value["profiles"][0]["credential"]
            if failure == "missing": value["profiles"][0]["credential"] = None
            elif failure == "file": c["storage"] = {"kind":"developmentFile", "generationId":probe.A}
            elif failure == "origin": c["origin"] = "http://127.0.0.1:46083"
            elif failure == "revision": c["revision"] = 2
            elif failure == "service": c["service"] = "app.loomlight"
            elif failure == "uuid": c["credentialId"] = "not-owned"
            elif failure == "cleanup": value["cleanup"] = []
            elif failure == "other": value["profiles"][1]["settings"]["label"] = "Changed"
            elif failure == "extra-profile": value["profiles"].append(dict(value["profiles"][1], profileId="ffffffff-ffff-4fff-8fff-ffffffffffff"))
            elif failure == "duplicate-profile": value["profiles"].append(copy.deepcopy(value["profiles"][0]))
            elif failure == "reorder": value["profiles"].reverse()
            elif failure == "store-revision": value["revision"] += 1
            elif failure == "unknown": value["unproved"] = True
            elif failure == "profile-unknown": value["profiles"][0]["unproved"] = True
            elif failure == "credential-unknown": c["unproved"] = True
            with self.subTest(failure=failure), self.assertRaises(ValueError):
                probe.validate_saved(old, value, probe.A)

        replacement = copy.deepcopy(saved)
        replacement["revision"] += 3
        replacement["profiles"][0]["revision"] += 1
        replacement["profiles"][0]["credential"] = dict(saved["profiles"][0]["credential"],
            credentialId="ffffffff-ffff-4fff-8fff-ffffffffffff", revision=2)
        probe.validate_saved(saved, replacement, probe.A)
        replacement["profiles"][0]["credential"]["credentialId"] = saved["profiles"][0]["credential"]["credentialId"]
        with self.assertRaises(ValueError): probe.validate_saved(saved, replacement, probe.A)

    def test_native_report_rejects_zero_wrong_skipped_failed_and_overbudget_results(self):
        report = {"passed":True, "cleanupComplete":True,"evidence":"runtime-ui-packaged","case":"studio-settings", "details":{"passed":True,"stage":"complete", "phase":1, "checks":probe.CHECKS[1]}}
        requests = [{"method":"GET","path":"/v1/models","label":"alpha", "accepted":True}, {"method":"GET","path":"/v1/models","label":"alpha", "accepted":True}]
        probe.check_report(1, report, requests, 0)
        for failure in ["zero", "skipped", "failed", "cleanup", "wrong-phase", "missing-checks", "overbudget", "wrong-key", "wrong-exit", "wrong-envelope", "wrong-method", "wrong-path", "inner-failed"]:
            value, sent, code = copy.deepcopy(report), copy.deepcopy(requests), 0
            if failure == "zero": sent.clear()
            elif failure == "skipped": value["details"]["stage"] = "skipped"
            elif failure == "failed": value["passed"] = False
            elif failure == "cleanup": value["cleanupComplete"] = False
            elif failure == "wrong-phase": value["details"]["phase"] = 2
            elif failure == "missing-checks": value["details"]["checks"] = []
            elif failure == "overbudget": sent += requests
            elif failure == "wrong-key": sent[1]["accepted"] = False
            elif failure == "wrong-exit": code = 1
            elif failure == "wrong-envelope": value["evidence"] = "unrelated"
            elif failure == "wrong-method": sent[0]["method"] = "POST"
            elif failure == "wrong-path": sent[0]["path"] = "/other"
            elif failure == "inner-failed": value["details"]["passed"] = False
            with self.subTest(failure=failure), self.assertRaises(ValueError):
                probe.check_report(1, value, sent, code)

if __name__ == "__main__":
    unittest.main()
