"""Bounded public Windows fixture; native dialog input uses Computer Use separately.

No installer execution, real credential, native enumeration, or automatic retry.
Receipts/packages are ignored. A started build/launch cannot be repeated.
"""
import argparse
from collections import Counter
import copy
import ctypes
import hashlib
import http.server
import json
import os
from pathlib import Path
import shutil
import subprocess
import platform
import sys
import tempfile
import tarfile
import tomllib
import threading
import time
import uuid

APP = Path(__file__).resolve().parents[1]
FIXTURE = APP / "tests/fixtures/windows-studio-credentials.json"
OUTPUT = APP / ".toolchains/windows-studio"
ACCEPTANCE = False
COMBINED_ATTEMPTS = 3
REPLACEMENT = False
SEQUENCE = None
COMPLETION_RUN = None
OBSERVATION_SECONDS = 180
RELOAD = APP / "tests/fixtures/windows-studio-credential-reload-failure.json"
REQUIRED_PERMISSIONS = {"src-tauri/permissions/core-request.toml",
                        "src-tauri/permissions/autogenerated/core_request.toml",
                        "src-tauri/permissions/autogenerated/complete_application_close.toml"}
A = "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa"
B = "bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb"
KEYS = {"alpha": "loomlight-public-windows-alpha", "beta": "loomlight-public-windows-beta",
        "gamma": "loomlight-public-windows-gamma"}
SCHEDULE = {1: ["alpha", "alpha"], 2: ["alpha", "beta"]}
BUILD_SECONDS = 1200
RUN_SECONDS = 300
COMMON_CHECKS = ["Fixed Windows phase selected", "Shared v2 profiles and foreign cleanup retained",
                 "Explicit authenticated discovery completed in this action", "Explicit authenticated discovery completed in this action",
                 "Discovery did not persist profile changes", "Discovery did not persist profile changes", "WebView contains no secret field"]
CHECKS = {
    1: COMMON_CHECKS + ["Initial fixture has no native keys", "Retained-field Retry saved A while foreign cleanup remained pending",
                        "Failed native entry then Cancel preserved complete redacted snapshot"],
    2: COMMON_CHECKS + ["Full process reopen reused both remembered keys without discovery", "Replacement preserved B and retired only owned A",
                        "Removal disabled A and preserved B", "All Windows keys/profiles removed; foreign owned cleanup retained"],
}
RELOAD_CHECKS = json.loads(RELOAD.read_text(encoding="utf-8"))["checks"]

def select_acceptance(combined_attempts=3, replacement=False, sequence=None):
    global OUTPUT, ACCEPTANCE, COMBINED_ATTEMPTS, REPLACEMENT, SEQUENCE
    if combined_attempts not in (3, 10) or replacement and combined_attempts != 10:
        raise ValueError("Explicit selected combined allowance required")
    if sequence is not None and (not replacement or combined_attempts != 10 or sequence < 10 or sequence % 2):
        raise ValueError("Fresh even phase-1 sequence identity required")
    SEQUENCE = sequence
    ACCEPTANCE = True
    COMBINED_ATTEMPTS = combined_attempts
    REPLACEMENT = replacement
    OUTPUT = APP / ".toolchains/windows-studio-acceptance"

def selected_run(phase):
    if COMPLETION_RUN is not None: return 14 if phase == 1 else COMPLETION_RUN
    if SEQUENCE is not None: return SEQUENCE + phase - 1
    return (8 if phase == 1 else 9) if REPLACEMENT else (6 if phase == 1 else 7)

def state_path():
    if COMPLETION_RUN is not None: return OUTPUT / "state-sequence-14.json"
    if SEQUENCE is not None: return OUTPUT / f"state-sequence-{SEQUENCE}.json"
    return OUTPUT / ("state-replacement.json" if REPLACEMENT else "state.json")

def combined_budget_check(kind=None):
    if COMPLETION_RUN is not None:
        builds = len(list(OUTPUT.glob("build-*-attempt.json")))
        runs = len(list(OUTPUT.glob("run-*-attempt.json")))
        if builds > 6 or runs > 9 or (kind == "build" and builds >= 6) or (kind == "launch" and runs >= 9):
            raise ValueError("Additional allowance exhausted: two builds / three launches above four / six")
        return {"combinedAttemptLimit":15,"combinedAttemptsBefore":builds+runs,
                "additionalBuildsBefore":builds-4,"additionalLaunchesBefore":runs-6}
    consumed = len(list(OUTPUT.glob("build-*-attempt.json"))) + len(list(OUTPUT.glob("run-*-attempt.json")))
    if consumed >= COMBINED_ATTEMPTS:
        raise ValueError("Selected combined build/launch allowance exhausted; no renewal")
    return {"combinedAttemptLimit":COMBINED_ATTEMPTS,"combinedAttemptsBefore":consumed}

def digest(value):
    return hashlib.sha256(json.dumps(value, sort_keys=True, separators=(",", ":")).encode()).hexdigest()

def reserve(paths):
    # Refuse *any* colliding output before exclusive attempt creation/dispatch.
    if any(p.exists() or p.is_symlink() for p in paths):
        raise ValueError("Acceptance receipt collision; preserve existing attempt")

def validate_elapsed(elapsed, limit):
    if not isinstance(elapsed, (int, float)) or not 0 < elapsed <= limit:
        raise ValueError("Required deadline missed")

def complete_inputs_match(built, current):
    required = {"sources", "nodeInstalled", "cargoInstalled", "resolved", "tools", "windows", "machine", "environmentDigest", "msvc", "sdk", "commit", "diffDigest", "generatedBefore"}
    if not isinstance(built, dict) or set(built) != required or not isinstance(current, dict) or set(current) != required:
        return False
    # The existing external-controller exception remains narrow; all other
    # installed/generated/toolchain/configuration data are frozen byte-for-byte.
    return (package_inputs_match(built["sources"], current["sources"])
            and {k:v for k,v in built.items() if k != "sources"} == {k:v for k,v in current.items() if k != "sources"})

def read(path):
    return json.loads(path.read_text(encoding="utf-8"))

def write(path, value, exclusive=False):
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("x" if exclusive else "w", encoding="utf-8") as file:
        json.dump(value, file, indent=2)

def sha(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()

def root_from_state():
    root = Path(read(state_path())["root"]).resolve()
    prefix = "loomlight-studio-windows-acceptance-" if ACCEPTANCE else "loomlight-studio-windows-"
    if root.parent != Path(tempfile.gettempdir()).resolve() or not root.name.startswith(prefix) or root.is_symlink():
        raise ValueError("Synthetic root refused")
    return root

def validate_saved(old, next_store, profile):
    before = next(p for p in old["profiles"] if p["profileId"] == profile)
    after = next(p for p in next_store["profiles"] if p["profileId"] == profile)
    c = after["credential"]
    if (after["settings"] != before["settings"] or after["disabled"] or after["revision"] != before["revision"] + 1
            or not isinstance(c, dict) or c == before["credential"] or "storage" in c
            or set(c) - {"credentialId", "origin", "revision", "service"}
            or c.get("service", "app.loomlight.desktop.ai.v1") != "app.loomlight.desktop.ai.v1"
            or c.get("origin") != "http://127.0.0.1:46082"
            or c.get("revision") != (before["credential"]["revision"] + 1 if before["credential"] else 1)):
        raise ValueError("Native save gate refused")
    parsed = uuid.UUID(c["credentialId"])
    if str(parsed) != c["credentialId"] or parsed.version != 4:
        raise ValueError("Unowned native identity")
    if before["credential"] and c["credentialId"] == before["credential"]["credentialId"]:
        raise ValueError("Replacement reused a retired identity")
    # This fixed fixture stages/publishes (+2), then removes a retired native
    # reference (+1 on replacement). Compare the entire expected store so extra,
    # duplicate/reordered profiles and unrelated/unknown fields cannot pass.
    expected = copy.deepcopy(old)
    expected["revision"] += 3 if before["credential"] else 2
    saved = next(p for p in expected["profiles"] if p["profileId"] == profile)
    saved.update(credential=c, revision=before["revision"] + 1, disabled=False)
    if next_store != expected:
        raise ValueError("Complete native save snapshot changed unexpectedly")

def check_report(phase, report, requests, code, reload=False):
    if (code != 0 or report.get("passed") is not True or report.get("cleanupComplete") is not True
            or report.get("evidence") != "runtime-ui-packaged" or report.get("case") != "studio-settings"
            or report.get("details", {}).get("passed") is not True
            or report.get("details", {}).get("stage") != "complete" or report["details"].get("phase") != phase
            or Counter(report["details"].get("checks", [])) != Counter(CHECKS[phase] + (RELOAD_CHECKS if reload else []))
            or len(requests) != 2 or any(r.get("accepted") is not True or r.get("method") != "GET"
                                       or r.get("path") != "/v1/models" for r in requests)
            or [r["label"] for r in requests] != SCHEDULE[phase]):
        raise ValueError("Native report/count/deadline gate refused")
    if reload and (phase != 2 or report["details"].get("reloadResponse") != read(RELOAD)["expectedResponse"]):
        raise ValueError("Exact Windows reload response missing")

def validate_client_timings(report):
    timings = report.get("details", {}).get("clientTimings")
    if not isinstance(timings, list) or len(timings) != 2:
        raise ValueError("Two actual client discovery timings required")
    last = 0
    for timing in timings:
        if not isinstance(timing, dict) or set(timing) != {"actionStarted", "requestStarted", "requestEnded", "completed"}:
            raise ValueError("Complete client timing fields required")
        values = [timing[k] for k in ("actionStarted", "requestStarted", "requestEnded", "completed")]
        if any(not isinstance(v, (int, float)) or isinstance(v, bool) for v in values) or not last <= values[0] <= values[1] < values[2] <= values[3]:
            raise ValueError("Ordered client timing required")
        validate_elapsed((values[2] - values[1]) / 1000, 15)
        if not 0 <= (values[3] - values[2]) / 1000 <= 2:
            raise ValueError("Client cleanup deadline exceeded")
        validate_elapsed((values[3] - values[0]) / 1000, 17)
        last = values[3]


def validate_removed(beta, final):
    expected = copy.deepcopy(beta)
    expected["revision"] += 6  # two disable/cleanup pairs (+2), two profile removals (+1)
    expected["profiles"] = []
    if final != expected:
        raise ValueError("Complete removal/active-generation snapshot refused")

def validate_prior(receipt, package_hash):
    check_report(1, receipt.get("report", {}), receipt.get("requests", []), receipt.get("exitCode"))
    validate_elapsed(receipt.get("elapsedSeconds"), 300)
    if receipt.get("run") != selected_run(1) or receipt.get("passed") is not True or receipt.get("stopped") is not True or receipt.get("pidAbsent") is not True or receipt.get("packageSha256") != package_hash:
        raise ValueError("Acceptance phase 2 requires complete selected phase-1 exit on same package")

def validate_observations(phase, value):
    expected = (["alpha-entry", "alpha-refusal", "alpha-retry", "gamma-entry", "gamma-confirmation", "cancel-entry", "stale-refusal", "cancel", "get-alpha-1", "get-alpha-2", "exit"]
                if phase == 1 else ["get-alpha", "beta-entry", "beta-confirmation", "reload-required", "read-only-retry", "get-beta", "exit"])
    if COMPLETION_RUN is not None and phase == 2:
        expected = ["reopened", "get-alpha", "beta-entry", "beta-confirmation", "reload-required", "read-only-retry", "get-beta", "removed", "complete", "exit"]
    if value.get("phase") != phase or value.get("run") != selected_run(phase) or [e.get("name") for e in value.get("events", [])] != expected:
        raise ValueError("Ordered native/UI observation evidence missing")
    last = 0
    for event in value["events"]:
        start, end = event.get("startSeconds", -1), event.get("endSeconds", -1)
        limit = OBSERVATION_SECONDS if COMPLETION_RUN is not None and phase == 2 else 120 if event["name"].endswith("-entry") else 17 if event["name"].startswith("get-") else 15
        if not 0 <= start <= end <= RUN_SECONDS or start < last or event.get("passed") is not True:
            raise ValueError("Native action order/result/deadline refused")
        validate_elapsed(end - start, limit)
        if event["name"].startswith("get-"):
            validate_elapsed(event.get("requestSeconds"), 15)
            cleanup = event.get("cleanupSeconds")
            if (not isinstance(cleanup, (int, float)) or not 0 <= cleanup <= 2
                    or (COMPLETION_RUN is None and event["requestSeconds"] + cleanup > end - start)):
                raise ValueError("GET/cleanup subdeadline refused")
        last = end
    required = (["maskedNativeField", "failedSaveRetainedInput", "retryWithoutRetyping", "staleSaveRetainedInput", "cancelAfterExactRestore"]
                if phase == 1 else ["maskedNativeField", "exactReloadStatus", "allMutationDiscoveryControlsDisabled", "readOnlyRetryEnabled", "restoredConfiguredA"])
    if value.get("observed") != dict.fromkeys(required, True):
        raise ValueError("Native UI capture/refusal/restoration proof missing")
    # Confirmation/fault/restore work must stay inside each original entry cap.
    events = {e["name"]:e for e in value["events"]}
    pairs = [("alpha-entry", "alpha-retry"), ("gamma-entry", "gamma-confirmation"), ("cancel-entry", "cancel")] if phase == 1 else [("beta-entry", "beta-confirmation")]
    for first, final in pairs:
        validate_elapsed(events[final]["endSeconds"] - events[first]["startSeconds"], 120)

def validate_probe_only_reuse(package):
    """Reuse actual run-14 evidence, explicitly recording a different probe binary."""
    old = read(OUTPUT / "build-6.json")
    prior = read(OUTPUT / "run-14.json")
    validate_prior(prior, old["sha256"])
    validate_client_timings(prior["report"])
    validate_observations(1, read(OUTPUT / "run-14-observed.json"))
    allowed = {"scripts/windows-studio-credentials.py", "scripts/test_windows_studio_credentials.py",
               "src-tauri/src/windows_studio_probe.js", "src-tauri/src/windows_studio_probe.rs",
               "src-tauri/src/main.rs"}
    before, after = old["sourceInputs"], package["sourceInputs"]
    changed = {k for k in before.keys() | after.keys() if before.get(k) != after.get(k)}
    if not changed or not changed.issubset(allowed):
        raise ValueError("Production inputs changed; run-14 reuse requires reassessment")
    # main.rs is shared: independently require its only change to be this exact
    # opt-in watchdog block, rather than excluding the whole production file.
    original = subprocess.run(["git", "show", "4698a88:app/src-tauri/src/main.rs"], cwd=APP,
                              capture_output=True, text=True, check=True).stdout
    current = (APP / "src-tauri/src/main.rs").read_text()
    start = current.index("                    // Only the opt-in Windows phase-2 walkthrough")
    end = current.index("                    while started.elapsed()", start)
    normalized = current[:start] + '                    let limit = if case == "branches-interactive" { 900 } else { 300 };\n' + current[end:]
    if normalized != original:
        raise ValueError("Shared main.rs contains changes outside probe watchdog")
    receipt = {"priorRun":14,"priorPackageSha256":old["sha256"],"newPackageSha256":package["sha256"],
               "changedInputs":sorted(changed),"unchangedProductionEvidenceReused":True,
               "sameBinary":False,"rootSha256":sha(root_from_state() / "ai-profiles.json")}
    write(OUTPUT / f"run-{COMPLETION_RUN}-reuse.json", receipt, exclusive=True)

def await_observations(prefix, started, exited_monotonic=None):
    # The host observes actual exit before publishing. Completion gives receipt
    # collection its own observation bound, separately from application shutdown.
    deadline = min((exited_monotonic if exited_monotonic is not None else time.monotonic()) + (OBSERVATION_SECONDS if COMPLETION_RUN else 15),
                   started + RUN_SECONDS)
    path = OUTPUT / f"{prefix}-observed.json"
    while not path.is_file():
        if time.monotonic() >= deadline:
            raise ValueError("Actual native observation receipt missing within exit/launch cap")
        time.sleep(0.02)
    if time.monotonic() >= deadline:
        raise ValueError("Actual native observation receipt late")
    return read(path)

def native_input_clock(run, entry_start_seconds):
    """File-only clock guard to call immediately before supported native input."""
    if not ACCEPTANCE or run not in (selected_run(1), selected_run(2)):
        raise ValueError("Selected native launch clock required")
    prefix = f"run-{run}"
    if (OUTPUT / f"{prefix}.json").exists():
        raise ValueError("Native run is terminal; no UI reacquisition/input")
    launch = read(OUTPUT / f"{prefix}-launch.json")
    now = time.monotonic()
    elapsed = now - launch["startedMonotonic"]
    if (not isinstance(entry_start_seconds, (int, float)) or isinstance(entry_start_seconds, bool)
            or not 0 <= entry_start_seconds <= elapsed < RUN_SECONDS
            or elapsed - entry_start_seconds >= 120):
        raise ValueError("Whole entry/launch clock exhausted; native input refused")
    return {"monotonic":now,"seconds":elapsed,"entryElapsedSeconds":elapsed-entry_start_seconds}

def pid_absent(pid):
    listing = subprocess.run(["tasklist", "/FI", f"PID eq {pid}", "/FO", "CSV", "/NH"], capture_output=True, text=True, timeout=2, check=True).stdout
    return f'"{pid}"' not in listing

def confirm_reload():
    if not ACCEPTANCE:
        raise ValueError("Reload acknowledgement is selected acceptance phase 2 only")
    run = selected_run(2)
    prefix = f"run-{run}"
    launch = read(OUTPUT / f"{prefix}-launch.json")
    if (OUTPUT / f"{prefix}.json").exists() or time.monotonic() - launch["startedMonotonic"] >= RUN_SECONDS or pid_absent(launch["pid"]):
        raise ValueError("Recorded selected phase 2 is not live within deadline")
    root = root_from_state()
    if read(root / ".studio-windows-step.json") != {"phase":"2", "step":"beta-reload-required"}:
        raise ValueError("Confirmed beta reload UI is not current")
    observed = read(OUTPUT / f"{prefix}-reload-observed.json")
    if (observed.get("run") != run or observed.get("phase") != 2
            or observed.get("saveStatus") != read(RELOAD)["expectedResponse"]["saveStatus"]
            or observed.get("controlsDisabled") is not True or observed.get("retryEnabled") is not True
            or observed.get("profilesSha256") != sha(root / ".studio-windows-2-beta-reload-required.json")
            or not observed.get("captures")):
        raise ValueError("Actual Windows reload UI capture missing")
    validate_elapsed(observed["endSeconds"] - observed["startSeconds"], OBSERVATION_SECONDS if COMPLETION_RUN else 15)
    if not 0 <= observed["startSeconds"] < observed["endSeconds"] <= time.monotonic() - launch["startedMonotonic"] <= RUN_SECONDS:
        raise ValueError("Reload UI capture deadline refused")
    for capture in observed["captures"]:
        path = OUTPUT / capture["file"]
        if path.resolve().parent != OUTPUT.resolve() or path.suffix.lower() not in (".png", ".jpg", ".jpeg", ".webp") or sha(path) != capture["sha256"] or path.stat().st_size != capture["bytes"]:
            raise ValueError("Owned Windows UI capture identity refused")
    # The unchanged packaged fixture uses logical acknowledgement 7. External
    # launch/capture receipts retain the selected physical run identity.
    write(root / ".studio-windows-reload-observed.json", {"run":7,"phase":2,"observed":True}, exclusive=True)

def check_cancel_report(report, requests, code, before, after, observed):
    status = "Credential entry cancelled; saved profile unchanged."
    details = report.get("details", {})
    # The unchanged packaged phase expects a Save, so it deliberately rejects a
    # Cancel. Accept only this separately selected zero-GET Cancel assertion; keep
    # the packaged full-flow result false in its terminal receipt.
    if (code != 1 or report.get("passed") is not False or report.get("cleanupComplete") is not True
            or report.get("evidence") != "runtime-ui-packaged" or report.get("case") != "studio-settings"
            or details.get("passed") is not False
            or requests != [] or details.get("phase") != 1 or details.get("stage") != "alpha-entry"
            or details.get("nativeStatus") != status or details.get("error") != "Error: Native entry result: " + status
            or Counter(details.get("checks", [])) != Counter(["Fixed Windows phase selected",
                "Shared v2 profiles and foreign cleanup retained", "Initial fixture has no native keys"])
            or before != after or observed != {"failedSaveRetainedInput": True, "cancelAfterExactRestore": True}):
        raise ValueError("Targeted Cancel proof refused")

def native_present(profile):
    c = profile["credential"]
    # Audit only exact synthetic app-created identities from this fixture's own
    # snapshots. Never enumerate or return/read a blob into Python/renderer data.
    if profile["profileId"] not in [A, B] or "storage" in c or c.get("service", "app.loomlight.desktop.ai.v1") != "app.loomlight.desktop.ai.v1" or c["origin"] != "http://127.0.0.1:46082":
        raise ValueError("Native audit ownership refused")
    identity = uuid.UUID(c["credentialId"])
    if identity.version != 4 or str(identity) != c["credentialId"]:
        raise ValueError("Native audit identity refused")
    target = "app.loomlight.desktop.ai.v1/provider/" + profile["profileId"] + "/" + c["credentialId"]
    api = ctypes.WinDLL("advapi32", use_last_error=True)
    api.CredReadW.argtypes = [ctypes.c_wchar_p, ctypes.c_uint32, ctypes.c_uint32, ctypes.POINTER(ctypes.c_void_p)]
    api.CredFree.argtypes = [ctypes.c_void_p]
    pointer = ctypes.c_void_p()
    if api.CredReadW(target, 1, 0, ctypes.byref(pointer)):
        api.CredFree(pointer)
        return True
    if ctypes.get_last_error() == 1168:
        return False
    raise ValueError("Native audit unavailable")

def prepare(preserve_owned_prior=False):
    if state_path().exists():
        raise ValueError("Fixture already prepared; do not renew")
    if ACCEPTANCE:
        reserve([state_path(), OUTPUT / f"run-{selected_run(1)}-attempt.json", OUTPUT / f"run-{selected_run(2)}-attempt.json"]
                + ([] if SEQUENCE is not None else [OUTPUT / f"build-{5 if REPLACEMENT else 3}-attempt.json"]))
    if REPLACEMENT:
        # This amendment replaces the specific known empty-key failed run 6.
        # Unknown/partly saved roots still require their own recovery selection.
        previous = SEQUENCE - 2 if SEQUENCE is not None else 6
        prior = read(OUTPUT / f"run-{previous}.json")
        previous_state = ("state-replacement.json" if previous == 8 else f"state-sequence-{previous}.json") if SEQUENCE is not None else "state.json"
        old_root = Path(read(OUTPUT / previous_state)["root"])
        if SEQUENCE is not None and not pid_absent(read(OUTPUT / f"run-{previous}-launch.json")["pid"]):
            raise ValueError("Previous dispatch still live or uncertain; no fresh root")
        if (prior.get("passed") is not False or prior.get("stopped") is not True or prior.get("pidAbsent") is not True):
            raise ValueError("Previous dispatch is not conclusively terminal")
        if preserve_owned_prior:
            if SEQUENCE is None or prior.get("report", {}).get("details", {}).get("error") != "Error: Client discovery timing missing":
                raise ValueError("Explicit known post-Cancel timing failure required")
            alpha = read(old_root / ".studio-windows-1-alpha-saved.json")
            gamma = read(old_root / ".studio-windows-1-gamma-saved.json")
            validate_saved(read(FIXTURE), alpha, A)
            validate_saved(alpha, gamma, B)
            expected = (old_root / ".studio-windows-1-gamma-saved.json").read_bytes()
            if prior.get("requests") != [{"method":"GET","path":"/v1/models","label":"alpha","accepted":True}] or any(
                path.read_bytes() != expected for path in [old_root / "ai-profiles.json", old_root / ".studio-windows-1-cancelled.json", OUTPUT / f"run-{previous}-cancel-before.bin"]):
                raise ValueError("Known saved prior bytes/requests differ; preserve without recovery")
        elif (prior.get("requests") != [] or (old_root / "ai-profiles.json").read_bytes() != FIXTURE.read_bytes()
                or any(old_root.glob(".studio-windows-1-*-saved.json"))):
            raise ValueError("Approved known empty-key replacement prerequisite missing")
    root = Path(tempfile.mkdtemp(prefix="loomlight-studio-windows-acceptance-" if ACCEPTANCE else "loomlight-studio-windows-"))
    (root / "ai-profiles.json").write_bytes(FIXTURE.read_bytes())
    write(state_path(), {"root": str(root), "fixtureSha256": sha(FIXTURE), **({"preservedOwnedPriorRun":previous} if preserve_owned_prior else {})}, exclusive=True)
    print(json.dumps({"prepared": True, "root": str(root), "builds": 0, "runs": 0, "gets": 0}))

def source_inputs():
    paths = [APP / name for name in ["Cargo.lock", "Cargo.toml", "package-lock.json",
             "package.json", "index.html", "vite.config.ts", "tsconfig.json", "rust-toolchain.toml"]]
    paths += [p for p in APP.iterdir() if p.is_file()]
    paths += [FIXTURE, RELOAD, Path(__file__)]
    paths += [p for p in (APP / "scripts").rglob("*") if p.is_file() and "__pycache__" not in p.parts]
    for directory in [APP / "src", APP / "src-core", APP / "src-tauri"]:
        paths += [p for p in directory.rglob("*") if p.is_file()
                  and not any(part in ["gen", "target"] for part in p.relative_to(APP).parts)]
    for directory in [APP / "public", APP / ".cargo"]:
        if directory.exists():
            paths += [p for p in directory.rglob("*") if p.is_file()]
    inputs = {str(p.relative_to(APP)).replace("\\", "/"): sha(p) for p in sorted(set(paths))}
    for directory in [APP / "public", APP / ".cargo", APP.parent / ".cargo"]:
        label = os.path.relpath(directory, APP).replace("\\", "/")
        inputs["$presence/" + label] = "present" if directory.exists() else "absent"
        if directory == APP.parent / ".cargo" and directory.exists():
            inputs.update({"../.cargo/" + p.relative_to(directory).as_posix(): sha(p) for p in directory.rglob("*") if p.is_file()})
    return inputs

def package_inputs_match(packaged, current):
    # Only this external runner can change without rebuilding. Every packaged
    # runtime/probe/schema/dependency input must still match the build receipt.
    controller = "scripts/windows-studio-credentials.py"
    required = {"Cargo.lock", "Cargo.toml", "package-lock.json", "package.json", "index.html",
                "vite.config.ts", "tsconfig.json", "rust-toolchain.toml",
                "src-tauri/Cargo.toml", "src-tauri/build.rs", "src-tauri/tauri.conf.json",
                "tests/fixtures/windows-studio-credentials.json",
                "tests/fixtures/windows-studio-credential-reload-failure.json"} | REQUIRED_PERMISSIONS
    # Inventory comes independently from the actual tree, including *all*
    # permissions/optional presence. Two equally incomplete handcrafted maps fail.
    required.update(source_inputs())
    if not required.issubset(packaged) or not required.issubset(current):
        return False
    return ({k: v for k, v in packaged.items() if k != controller}
            == {k: v for k, v in current.items() if k != controller})

def run_prefix(run, phase):
    choices = {(1, 1): "phase-1", (2, 1): "phase-1-retry",
               (3, 1): "phase-1-final", (3, 2): "phase-2", (4, 2): "phase-2",
               (5, 1): "phase-1-cancel-proof"}
    if ACCEPTANCE:
        choices = {(selected_run(1), 1): f"run-{selected_run(1)}", (selected_run(2), 2): f"run-{selected_run(2)}"}
    if (run, phase) not in choices:
        raise ValueError("Recorded run/phase selection required")
    return choices[(run, phase)]

def validate_partial_entry(receipt, alpha, gamma):
    # Preserve the failed entry-flow result. This only qualifies its two saved
    # snapshots as inputs to an independent reopen; it never accepts Cancel proof.
    report = receipt.get("report", {})
    details = report.get("details", {})
    if (receipt.get("run") != 3 or receipt.get("passed") is not False
            or receipt.get("exitCode") != 1 or receipt.get("stopped") is not True
            or receipt.get("requests") != [] or not 0 < receipt.get("elapsedSeconds", 0) <= RUN_SECONDS
            or report.get("cleanupComplete") is not True or report.get("passed") is not False
            or report.get("evidence") != "runtime-ui-packaged" or report.get("case") != "studio-settings"
            or details.get("passed") is not False
            or details.get("phase") != 1 or details.get("stage") != "cancel-entry"
            or details.get("error") != "Error: Timeout: cancel-entry"
            or Counter(details.get("checks", [])) != Counter(["Fixed Windows phase selected",
                "Shared v2 profiles and foreign cleanup retained", "Initial fixture has no native keys",
                "Retained-field Retry saved A while foreign cleanup remained pending"])):
        raise ValueError("Partial entry state refused; failed evidence remains failed")
    validate_saved(read(FIXTURE), alpha, A)
    validate_saved(alpha, gamma, B)

def tree_inputs(root):
    if not root.is_dir():
        raise ValueError("Required installed/generated input tree missing")
    return {p.relative_to(root).as_posix(): sha(p) for p in sorted(root.rglob("*")) if p.is_file()}

def generated_inputs():
    target = Path(os.environ["CARGO_TARGET_DIR"]) / "release/build"
    return {"tauri":tree_inputs(APP / "src-tauri/gen"), "cargoBuildOut":{
        p.relative_to(target).as_posix():sha(p) for p in sorted(target.glob("*/out/**/*")) if p.is_file()}}

def configure_npm_hook():
    """Use the verified CLI for Tauri's fixed npm hook, without installing npm."""
    node = Path(shutil.which("node") or "missing-node").resolve()
    cli = Path(os.environ.get("LOOMLIGHT_WINDOWS_NPM_CLI", "missing-npm")).resolve()
    if not node.is_file() or not cli.is_file() or any(c in str(node) + str(cli) for c in '\r\n"%!'):
        raise ValueError("Pinned npm hook paths unavailable or unsupported")
    directory = OUTPUT / "npm-hook"
    hook = directory / "npm.cmd"
    expected = f'@echo off\r\n"{node}" "{cli}" %*\r\n'.encode()
    directory.mkdir(parents=True, exist_ok=True)
    if hook.exists():
        if hook.read_bytes() != expected:
            raise ValueError("Existing npm hook differs; preserve it")
    else:
        with hook.open("xb") as file:
            file.write(expected)
    # Idempotent in this process; build and launch freeze the same PATH digest.
    entries = os.environ.get("PATH", "").split(os.pathsep)
    os.environ["PATH"] = os.pathsep.join([str(directory)] + [p for p in entries if p != str(directory)])
    result = subprocess.run(["cmd.exe", "/d", "/c", "npm --version"], cwd=APP,
                            capture_output=True, text=True, timeout=15, check=True)
    if result.stdout.strip() != "11.9.0" or result.stderr.strip():
        raise ValueError("Tauri npm hook did not resolve pinned npm 11.9.0")
    return {"sha256":sha(hook), "version":result.stdout.strip()}

def qualification_inputs():
    """Future build/launch preflight only. No installs, package build or store call."""
    sources = source_inputs()
    if not REQUIRED_PERMISSIONS.issubset(sources):
        raise ValueError("Complete permissions missing")
    if platform.system() != "Windows" or platform.machine().lower() not in ("amd64", "x86_64"):
        raise ValueError("Actual Windows x64 required")
    def output(args):
        return subprocess.run(args, cwd=APP, capture_output=True, text=True, timeout=30, check=True).stdout.strip()
    metadata = json.loads(output(["cargo", "metadata", "--locked", "--offline", "--format-version", "1", "--filter-platform", "x86_64-pc-windows-msvc"]))
    lock = tomllib.loads((APP / "Cargo.lock").read_text())
    locked = {(p["name"],p["version"]):p for p in lock["package"]}
    cargo = {}
    for package in metadata["packages"]:
        if package.get("source"):
            directory = Path(package["manifest_path"]).parent
            crate = Path(os.environ["CARGO_HOME"]) / "registry/cache" / directory.parent.name / (directory.name + ".crate")
            expected = locked[(package["name"],package["version"])].get("checksum")
            if not expected or sha(crate) != expected:
                raise ValueError("Cached Cargo archive does not match locked checksum")
            archive_files = {}
            # Ordinary registry extraction may have no vendor checksum manifest.
            # Verify installed bytes against the original locked archive read-only.
            with tarfile.open(crate) as archive:
                for member in archive.getmembers():
                    if member.isdir(): continue
                    parts = Path(member.name).parts
                    if not member.isfile() or len(parts)<2 or parts[0]!=directory.name or ".." in parts:
                        raise ValueError("Unsupported Cargo archive entry")
                    name = Path(*parts[1:]).as_posix()
                    data = archive.extractfile(member).read()
                    archive_files[name] = hashlib.sha256(data).hexdigest()
                    if sha(directory / name) != archive_files[name]:
                        raise ValueError("Installed Cargo bytes differ from locked archive")
            installed = tree_inputs(directory)
            if set(installed) - set(archive_files) - {".cargo-ok", ".cargo-checksum.json"}:
                raise ValueError("Unexpected installed Cargo input")
            vendor = read(directory / ".cargo-checksum.json") if (directory / ".cargo-checksum.json").exists() else None
            if vendor and (vendor.get("package") != expected or any(sha(directory / name) != value for name,value in vendor["files"].items())):
                raise ValueError("Vendor Cargo checksum mismatch")
            cargo[package["id"]] = {"lockedArchiveSha256":expected,"archiveFiles":archive_files,"vendorChecksumManifest":vendor,"installedFiles":installed}
    # Private absolute paths stay only in ignored receipts.
    safe_env = {k:os.environ[k] for k in ("PATH", "CARGO_HOME", "RUSTUP_HOME", "RUSTUP_TOOLCHAIN", "CARGO_TARGET_DIR", "CARGO_INCREMENTAL", "VCToolsVersion", "WindowsSDKVersion", "WindowsSdkDir", "INCLUDE", "LIB", "LIBPATH", "TEMP", "TMP", "LOOMLIGHT_WINDOWS_NPM_CLI") if k in os.environ}
    safe_env.update({k:hashlib.sha256(v.encode()).hexdigest() for k,v in os.environ.items()
                     if k.startswith(("CARGO_", "RUST", "TAURI", "VITE", "NODE_", "NPM_", "npm_", "CC", "CXX", "CL", "LINK", "LOOMLIGHT_"))})
    unexpected = [k for k in os.environ if os.environ[k] and (k.startswith(("RUSTFLAGS", "CARGO_ENCODED", "RUSTC_WRAPPER", "RUSTC_WORKSPACE_WRAPPER", "CARGO_PROFILE_", "CARGO_BUILD_", "CARGO_TARGET_", "TAURI_CONFIG", "VITE_")) or k in ("NODE_OPTIONS", "CL", "_CL_", "LINK", "_LINK_", "CC", "CXX")) and k != "CARGO_TARGET_DIR"]
    if unexpected:
        raise ValueError("Unexpected build-affecting override")
    npm_cli = Path(os.environ.get("LOOMLIGHT_WINDOWS_NPM_CLI", str(Path(shutil.which("npm") or "missing-npm").parent / "node_modules/npm/bin/npm-cli.js")))
    if not npm_cli.is_file():
        raise ValueError("Pinned npm CLI path unavailable; resolve in no-launch preflight")
    tools = {name: {"version":output(args), "sha256":sha(Path(shutil.which(args[0])))} for name,args in {
        "node":["node","--version"], "npm":["node",str(npm_cli),"--version"],
        "tauri":["node",str(APP / "node_modules/@tauri-apps/cli/tauri.js"),"--version"],
        "rustc":["rustc","-Vv"], "cargo":["cargo","-V"]}.items()}
    if not safe_env.get("VCToolsVersion") or not safe_env.get("WindowsSDKVersion"):
        raise ValueError("MSVC/Windows SDK identity missing")
    tools["python"] = {"version":sys.version,"sha256":sha(Path(sys.executable))}
    tools["npm"]["cliSha256"] = sha(npm_cli)
    tools["npm"]["hook"] = {"sha256":sha(OUTPUT / "npm-hook/npm.cmd"), "version":"11.9.0"}
    for name in ["rustc", "cargo"]:
        tools[name]["actualBinarySha256"] = sha(Path(output(["rustup", "which", name])))
    tools["msvc"] = {name:sha(Path(shutil.which(name))) for name in ["cl", "link", "rc"]}
    vc = Path(os.environ.get("VCToolsInstallDir", "missing-vc"))
    tools["msvcHeaders"] = tree_inputs(vc / "include")
    tools["msvcLibs"] = tree_inputs(vc / "lib/x64")
    rust = Path(output(["rustup", "which", "rustc"])).parent.parent
    tools["rustTargetLibs"] = tree_inputs(rust / "lib/rustlib/x86_64-pc-windows-msvc/lib")
    sdk = Path(os.environ.get("WindowsSdkDir", "missing-sdk"))
    tools["windowsSdkLibs"] = tree_inputs(sdk / "Lib" / safe_env["WindowsSDKVersion"].strip("\\/"))
    tools["windowsSdkHeaders"] = tree_inputs(sdk / "Include" / safe_env["WindowsSDKVersion"].strip("\\/"))
    return {"sources":sources,"nodeInstalled":tree_inputs(APP / "node_modules"), "cargoInstalled":cargo,
            "resolved":metadata["resolve"], "tools":tools,"windows":platform.platform(),"machine":platform.machine(),
            "environmentDigest":digest(safe_env),"msvc":safe_env["VCToolsVersion"],"sdk":safe_env["WindowsSDKVersion"],
            "commit":output(["git","rev-parse","HEAD"]), "diffDigest":digest(output(["git","diff","HEAD","--",".",":!scripts/windows-studio-credentials.py"])),
            "generatedBefore":tree_inputs(APP / "src-tauri/gen")}

def build(number):
    # Exclusive identities preserve the first package and failed native receipt.
    # Calling this does not grant another operation beyond the selected ledger.
    allowed = ((range(5, 15) if SEQUENCE is not None else (5,)) if REPLACEMENT else range(3, 13) if COMBINED_ATTEMPTS == 10 else (3,)) if ACCEPTANCE else (1, 2)
    if number not in allowed:
        raise ValueError("Recorded selected build required; allowance is not renewed")
    if ACCEPTANCE:
        combined_budget_check("build")
        reserve([OUTPUT / f"build-{number}-attempt.json", OUTPUT / f"build-{number}.json",
                 OUTPUT / f"build-{number}-terminal.json", OUTPUT / f"build-{number}.log",
                 OUTPUT / f"package-{number}"])
        configure_npm_hook()
    inputs = source_inputs()
    complete = qualification_inputs() if ACCEPTANCE else None
    if ACCEPTANCE:
        reserve([OUTPUT / f"build-{number}-attempt.json", OUTPUT / f"build-{number}.json",
                 OUTPUT / f"build-{number}-terminal.json", OUTPUT / f"build-{number}.log", OUTPUT / f"package-{number}"])
    started = time.monotonic()
    command = [shutil.which("node"), str(APP / "node_modules/@tauri-apps/cli/tauri.js"),
               "build", "--bundles", "nsis", "--", "--locked", "--offline"]
    write(OUTPUT / f"build-{number}-attempt.json", {"deadlineSeconds": BUILD_SECONDS,
          "startedMonotonic":started,"command":command,"sourceInputs":inputs,"completeInputs":complete,
          **(combined_budget_check("build") if ACCEPTANCE else {})}, exclusive=True)
    process, code, passed, failure, absent = None, None, False, None, None
    try:
        with (OUTPUT / f"build-{number}.log").open("x", encoding="utf-8") as log:
            process = subprocess.Popen(command, cwd=APP, stdout=log, stderr=subprocess.STDOUT)
            try:
                code = process.wait(timeout=max(0.001, BUILD_SECONDS - (time.monotonic() - started)))
            except subprocess.TimeoutExpired:
                subprocess.run(["taskkill", "/PID", str(process.pid), "/T", "/F"], stdout=log, stderr=subprocess.STDOUT, timeout=2, check=False)
                code = process.wait(timeout=2)
                raise ValueError("Package deadline exceeded; owned build tree terminated, no retry")
        if code or source_inputs() != inputs:
            raise ValueError("Package failed or source inputs changed; no automatic retry")
        if ACCEPTANCE:
            absent = pid_absent(process.pid)
            if not absent:
                raise ValueError("External build PID absence unproved")
            after = qualification_inputs()
            # Tauri regeneration is recorded, never silently treated as equality.
            if after != complete:
                write(OUTPUT / f"build-{number}-input-mismatch.json", {"before":complete,"after":after}, exclusive=True)
                raise ValueError("Complete build inputs changed; preserve build, no retry")
        source = Path(os.environ["CARGO_TARGET_DIR"]) / "release/loomlight.exe"
        destination = OUTPUT / f"package-{number}/loomlight.exe"
        destination.parent.mkdir()
        shutil.copy2(source, destination)
        installer = Path(os.environ["CARGO_TARGET_DIR"]) / "release/bundle/nsis/Loomlight_0.1.0_x64-setup.exe"
        shutil.copy2(installer, destination.parent / installer.name)
        receipt = {"passed":True,"elapsedSeconds":time.monotonic()-started,"executable":str(destination),
                   "sha256":sha(destination),"bytes":destination.stat().st_size,"sourceInputs":inputs,
                   "installerSha256":sha(destination.parent/installer.name),
                   "installerBytes":(destination.parent/installer.name).stat().st_size}
        if ACCEPTANCE:
            receipt.update(completeInputs=complete,command=command,distInputs=tree_inputs(APP / "dist"),generatedInputs=generated_inputs())
            receipt["elapsedSeconds"] = time.monotonic() - started
            validate_elapsed(receipt["elapsedSeconds"], BUILD_SECONDS)
        write(OUTPUT / f"build-{number}.json", receipt, exclusive=True)
        passed = True
        print(json.dumps({k:v for k,v in receipt.items() if k not in ("sourceInputs","completeInputs","distInputs","generatedInputs")}))
    except BaseException as error:
        failure = str(error)
        raise
    finally:
        if ACCEPTANCE:
            if absent is None and process is not None and process.poll() is not None:
                try:
                    absent = pid_absent(process.pid)
                except (OSError, subprocess.SubprocessError):
                    pass  # Unknown stays unknown; never convert missing proof to PASS.
            write(OUTPUT / f"build-{number}-terminal.json", {"build":number,"passed":passed,
                  "pid":process.pid if process is not None else None,"exitCode":code,
                  "stopped":process is None or process.poll() is not None,"pidAbsent":absent,
                  "startedMonotonic":started,"endedMonotonic":time.monotonic(),
                  "elapsedSeconds":time.monotonic()-started,"failure":failure}, exclusive=True)

def launch(phase, run, build_number, resume_partial=False, cancel_only=False):
    if COMPLETION_RUN is not None and phase != 2:
        raise ValueError("Completion reuses run 14; no phase-1 repetition")
    root = root_from_state()
    prefix = run_prefix(run, phase)
    allowed = (range(5,15) if SEQUENCE is not None else (5,)) if REPLACEMENT else range(3,13) if COMBINED_ATTEMPTS == 10 else (3,)
    if ACCEPTANCE and (build_number not in allowed or resume_partial or cancel_only):
        raise ValueError("Acceptance requires selected build and full phases only")
    if ACCEPTANCE:
        combined_budget_check("launch")
        reserve([OUTPUT / f"{prefix}{suffix}" for suffix in ["-attempt.json", "-launch.json", "-exit.json", ".json", ".stdout.log", ".stderr.log"]])
        configure_npm_hook()
        if phase == 1 and (root / "ai-profiles.json").read_bytes() != FIXTURE.read_bytes():
            raise ValueError("Acceptance requires exact fresh fixture bytes")
    if cancel_only:
        if (run, phase, build_number) != (5, 1, 2) or resume_partial or read(root / "ai-profiles.json") != read(FIXTURE):
            raise ValueError("Targeted Cancel requires explicit run 5, package 2 and exact empty-key fixture")
        if not read(OUTPUT / "phase-2.json").get("passed"):
            raise ValueError("Owned removal must already be proved before Cancel follow-up")
    elif run == 5:
        raise ValueError("Run 5 is only the separately approved targeted Cancel follow-up")
    before_cancel = (root / "ai-profiles.json").read_bytes() if cancel_only else None
    schedule = [] if cancel_only else SCHEDULE[phase]
    prior = "phase-1-final" if run == 4 else "phase-1-retry"
    if resume_partial:
        if (run, phase, build_number) != (4, 2, 2):
            raise ValueError("Partial resume is fixed to approved run 4/package 2")
        alpha = read(root / ".studio-windows-1-alpha-saved.json")
        gamma = read(root / ".studio-windows-1-gamma-saved.json")
        validate_partial_entry(read(OUTPUT / "phase-1-final.json"), alpha, gamma)
        readiness = read(OUTPUT / "run-4-partial-readiness.json")
        if read(root / "ai-profiles.json") != gamma or readiness != {"run":4,"priorPassed":False,"nativeKeysPresent":2,"restoredSha256":sha(root / "ai-profiles.json"),"cancelProof":False}:
            raise ValueError("Partial restored/native readiness refused")
    elif phase == 2 and not ACCEPTANCE and not read(OUTPUT / f"{prior}.json").get("passed"):
        raise ValueError("First native phase must pass")
    package = read(OUTPUT / f"build-{build_number}.json")
    if ACCEPTANCE:
        terminal = read(OUTPUT / f"build-{build_number}-terminal.json")
        if terminal.get("passed") is not True or terminal.get("stopped") is not True or terminal.get("pidAbsent") is not True or terminal.get("exitCode") != 0:
            raise ValueError("Complete build terminal/exit/PID proof missing")
        if package.get("passed") is not True or not complete_inputs_match(package.get("completeInputs"), qualification_inputs()) or package.get("distInputs") != tree_inputs(APP / "dist") or package.get("generatedInputs") != generated_inputs():
            raise ValueError("Complete installed/generated build inputs changed")
        if phase == 2:
            if COMPLETION_RUN is not None:
                validate_probe_only_reuse(package)
            else:
                validate_prior(read(OUTPUT / f"run-{selected_run(1)}.json"), package["sha256"])
            if (root / "ai-profiles.json").read_bytes() != (root / ".studio-windows-1-complete.json").read_bytes():
                raise ValueError("Complete prior root bytes changed")
    executable = Path(package["executable"])
    current_inputs = source_inputs()
    if sha(executable) != package["sha256"] or not package_inputs_match(package["sourceInputs"], current_inputs):
        raise ValueError("Tested package/source identity changed")
    if sha(FIXTURE) != read(state_path())["fixtureSha256"]:
        raise ValueError("Fixture identity changed")
    # This lightweight process inventory never launches an app or inspects its data.
    processes = subprocess.run(["tasklist", "/FI", "IMAGENAME eq loomlight.exe", "/FO", "CSV", "/NH"], capture_output=True, text=True, check=True).stdout
    if '"loomlight.exe"' in processes.lower():
        raise ValueError("A Loomlight process is already running; preserve its ownership")
    requests = []
    class Handler(http.server.BaseHTTPRequestHandler):
        def log_message(self, *_):
            pass
        def do_GET(self):
            index = len(requests)
            label = schedule[index] if index < len(schedule) else "over-budget"
            accepted = self.command == "GET" and self.path == "/v1/models" and index < len(schedule) and self.headers.get("Authorization") == "Bearer " + KEYS.get(label, "refused")
            requests.append({"method": self.command, "path": "/v1/models" if self.path == "/v1/models" else "refused-path", "label": label, "accepted": accepted})
            body = json.dumps({"data": [{"id": "loomlight-synthetic-model"}]} if accepted else {"error": "fixture refused"}).encode()
            self.send_response(200 if accepted else 403)
            self.send_header("Content-Type", "application/json")
            self.send_header("Content-Length", str(len(body)))
            self.end_headers()
            self.wfile.write(body)
        do_POST = do_PUT = do_DELETE = do_PATCH = do_HEAD = do_OPTIONS = do_GET
    env = dict(os.environ, LOOMLIGHT_RUNTIME_UI_PROBE="studio-settings", LOOMLIGHT_STUDIO_PROBE_ROOT=str(root), LOOMLIGHT_STUDIO_WINDOWS_PHASE=str(phase))
    if ACCEPTANCE:
        env["LOOMLIGHT_STUDIO_WINDOWS_EVIDENCE"] = "1"
    if ACCEPTANCE and phase == 2:
        env["LOOMLIGHT_STUDIO_WINDOWS_RELOAD_FAILURE"] = read(RELOAD)["selector"]
    elif "LOOMLIGHT_STUDIO_WINDOWS_RELOAD_FAILURE" in env:
        raise ValueError("Unexpected Windows reload selector")
    if any(k in env for k in ["LOOMLIGHT_STUDIO_DEV_CREDENTIAL_PHASE", "LOOMLIGHT_STUDIO_DEV_RELOAD_FAILURE"]):
        raise ValueError("Conflicting Mac fixture selector")
    write(OUTPUT / f"{prefix}-attempt.json", {"run": run, "phase": phase, "deadlineSeconds": RUN_SECONDS,
          **(combined_budget_check("launch") if ACCEPTANCE else {}),
          "getAllowance": len(schedule), "packageSha256": package["sha256"], "packagedInputsMatch": True,
          "partialEntryResume": resume_partial, "targetedCancelOnly": cancel_only,
          "builtControllerSha256": package["sourceInputs"]["scripts/windows-studio-credentials.py"],
          "currentControllerSha256": current_inputs["scripts/windows-studio-credentials.py"]}, exclusive=True)
    # The listener and process are created only after the exclusive attempt exists.
    try:
        server = http.server.ThreadingHTTPServer(("127.0.0.1", 46082), Handler)
    except OSError:
        if ACCEPTANCE:
            write(OUTPUT / f"{prefix}.json", {"passed":False,"run":run,"exitCode":None,"stopped":True,
                  "pidAbsent":True,"elapsedSeconds":0,"requests":[],"report":{},"packageSha256":package["sha256"],
                  "failure":"Listener unavailable after reservation; attempt consumed, no retry"}, exclusive=True)
        raise
    server.daemon_threads = True
    started = time.monotonic()
    started_unix = time.time()
    process, code, report = None, None, {}
    threading.Thread(target=server.serve_forever, daemon=True).start()
    try:
        with (OUTPUT / f"{prefix}.stdout.log").open("w", encoding="utf-8") as out, (OUTPUT / f"{prefix}.stderr.log").open("w", encoding="utf-8") as err:
            process = subprocess.Popen([str(executable)], env=env, stdout=out, stderr=err)
            write(OUTPUT / f"{prefix}-launch.json", {"run": run, "pid": process.pid, "startedMonotonic":started, "startedUnix":started_unix, "deadlineUnix": time.time() + RUN_SECONDS, "executable": str(executable), "sha256":sha(executable)}, exclusive=True)
            print(json.dumps({"phase": phase, "pid": process.pid, "deadlineSeconds": RUN_SECONDS}), flush=True)
            try:
                code = process.wait(timeout=max(0.001, RUN_SECONDS - (time.monotonic() - started)))
            except subprocess.TimeoutExpired:
                subprocess.run(["taskkill", "/PID", str(process.pid), "/T", "/F"], capture_output=True, timeout=2, check=False)
                process.wait(timeout=2)
                code = -1
        elapsed = time.monotonic() - started
        if ACCEPTANCE:
            write(OUTPUT / f"{prefix}-exit.json", {"run":run,"pid":process.pid,"exitCode":code,
                  "stopped":process.poll() is not None,"pidAbsent":pid_absent(process.pid),
                  "elapsedSeconds":elapsed}, exclusive=True)
        reports = [json.loads(line) for line in (OUTPUT / f"{prefix}.stdout.log").read_text().splitlines() if line.startswith('{')]
        report = next((r for r in reports if r.get("evidence") == "runtime-ui-packaged"), {})
        passed = False
        try:
            if cancel_only:
                check_cancel_report(report, requests, code, before_cancel, (root / "ai-profiles.json").read_bytes(),
                                    read(OUTPUT / "phase-1-cancel-proof-observed.json"))
            else:
                check_report(phase, report, requests, code, reload=ACCEPTANCE and phase == 2)
            validate_elapsed(elapsed, RUN_SECONDS)
            absent = pid_absent(process.pid) if ACCEPTANCE else process.poll() is not None
            if not absent:
                raise ValueError("External PID absence unproved")
            if ACCEPTANCE:
                validate_client_timings(report)
                validate_observations(phase, await_observations(prefix, started, started + elapsed))
            fixture = read(FIXTURE)
            if cancel_only:
                pass
            elif phase == 1:
                alpha = read(root / ".studio-windows-1-alpha-saved.json")
                gamma = read(root / ".studio-windows-1-gamma-saved.json")
                validate_saved(fixture, alpha, A)
                validate_saved(alpha, gamma, B)
                if gamma != read(root / ".studio-windows-1-cancelled.json"):
                    raise ValueError("Cancel changed profile snapshot")
                if ACCEPTANCE:
                    gamma_bytes = (root / ".studio-windows-1-gamma-saved.json").read_bytes()
                    for path in [root / ".studio-windows-1-cancelled.json", root / ".studio-windows-1-complete.json", OUTPUT / f"{prefix}-cancel-before.bin", root / "ai-profiles.json"]:
                        if path.read_bytes() != gamma_bytes:
                            raise ValueError("Cancel/discovery changed complete profile bytes")
                    for name in ["alpha", "cancel"]:
                        before = OUTPUT / f"{prefix}-{name}-before.bin"
                        if read(OUTPUT / f"{prefix}-{name}-restored.json")["restoredSha256"] != sha(before):
                            raise ValueError("Exact fault restoration missing")
                if not all(native_present(p) for p in gamma["profiles"]):
                    raise ValueError("Two native entries must remain for reopen")
            else:
                reopened = read(root / ".studio-windows-2-reopened.json")
                previous = ".studio-windows-1-gamma-saved.json" if resume_partial else ".studio-windows-1-complete.json"
                if reopened != read(root / previous):
                    raise ValueError("Reopen changed profiles")
                validate_saved(reopened, read(root / ".studio-windows-2-beta-saved.json"), A)
                final = read(root / "ai-profiles.json")
                beta = read(root / ".studio-windows-2-beta-saved.json")
                validate_removed(beta, final)
                if ACCEPTANCE:
                    for name in ["beta-reload-required", "beta-reloaded", "beta-saved"]:
                        if (root / f".studio-windows-2-{name}.json").read_bytes() != (root / ".studio-windows-2-beta-saved.json").read_bytes():
                            raise ValueError("Read-only Retry changed persistent bytes")
                    if (root / ".studio-windows-2-reopened.json").read_bytes() != (root / previous).read_bytes() or (root / ".studio-windows-2-complete.json").read_bytes() != (root / "ai-profiles.json").read_bytes():
                        raise ValueError("Reopen/final complete byte proof missing")
                identities = [reopened["profiles"][0], beta["profiles"][0], beta["profiles"][1]]
                if any(native_present(p) for p in identities):
                    raise ValueError("Retired/removed native entries still present")
            if ACCEPTANCE:
                validate_elapsed(time.monotonic() - (started + elapsed), OBSERVATION_SECONDS if COMPLETION_RUN else 15)
                elapsed = time.monotonic() - started
                validate_elapsed(elapsed, RUN_SECONDS)
            passed = True
        finally:
            write(OUTPUT / f"{prefix}.json", {"passed": passed, "run": run, "exitCode": code, "stopped": process.poll() is not None,
                  "pidAbsent":pid_absent(process.pid) if ACCEPTANCE else process.poll() is not None,
                  "packageSha256":package["sha256"], "elapsedSeconds": elapsed, "requests": requests, "report": report}, exclusive=True)
            if cancel_only:
                write(OUTPUT / "targeted-cancel-result.json", {"cancelProofPassed":passed,
                      "packagedFullFlowPassed":False,"run":5,"gets":len(requests),"sameSnapshot":before_cancel==(root / "ai-profiles.json").read_bytes()}, exclusive=True)
            print(json.dumps({"passed": passed, "phase": phase, "exitCode": code, "elapsedSeconds": elapsed, "gets": len(requests)}), flush=True)
    finally:
        server.shutdown()
        server.server_close()
        # Dispatch/report parsing/termination errors must still leave a failed
        # terminal record. The reserved attempt is consumed even if no PID exists.
        if ACCEPTANCE and not (OUTPUT / f"{prefix}.json").exists():
            write(OUTPUT / f"{prefix}.json", {"passed":False,"run":run,"exitCode":code,
                  "stopped":process is None or process.poll() is not None,"pidAbsent":None,
                  "packageSha256":package["sha256"],"elapsedSeconds":time.monotonic()-started,
                  "requests":requests,"report":report,"failure":"Dispatch/termination/report collection incomplete; no retry"}, exclusive=True)

def fault(action, name):
    root = root_from_state()
    prefix = next((p for p in ([f"run-{selected_run(1)}"] if ACCEPTANCE else ["phase-1-cancel-proof", "phase-1-final", "phase-1-retry", "phase-1"]) if (OUTPUT / f"{p}-launch.json").exists()), None)
    if prefix is None:
        raise ValueError("No recorded native launch")
    launch = read(OUTPUT / f"{prefix}-launch.json")
    if (OUTPUT / f"{prefix}.json").exists() or time.time() >= launch["deadlineUnix"]:
        raise ValueError("Native phase finished or deadline expired")
    if name not in ["alpha", "cancel"]:
        raise ValueError("Fixed failure step required")
    marker = read(root / ".studio-windows-step.json")
    if marker != {"phase": "1", "step": name + "-entry"}:
        raise ValueError("Native entry step not current")
    profiles = root / "ai-profiles.json"
    fault_name = (prefix + "-" + name) if ACCEPTANCE or prefix in ["phase-1-final", "phase-1-cancel-proof"] else name
    backup = OUTPUT / (fault_name + "-before.bin")
    fault_receipt = OUTPUT / (fault_name + "-fault.json")
    restored_receipt = OUTPUT / (fault_name + "-restored.json")
    reserve([backup, fault_receipt, restored_receipt] if action == "corrupt" else [restored_receipt])
    kernel = ctypes.WinDLL("kernel32", use_last_error=True)
    kernel.OpenProcess.argtypes = [ctypes.c_uint32, ctypes.c_int, ctypes.c_uint32]
    kernel.OpenProcess.restype = ctypes.c_void_p
    kernel.GetExitCodeProcess.argtypes = [ctypes.c_void_p, ctypes.POINTER(ctypes.c_uint32)]
    kernel.CloseHandle.argtypes = [ctypes.c_void_p]
    handle = kernel.OpenProcess(0x1000, 0, launch["pid"])
    code = ctypes.c_uint32()
    try:
        if not handle or not kernel.GetExitCodeProcess(handle, ctypes.byref(code)) or code.value != 259:
            raise ValueError("Recorded native process is no longer live")
    finally:
        if handle: kernel.CloseHandle(handle)
    if action == "corrupt":
        with backup.open("xb") as file:
            file.write(profiles.read_bytes())
        if name == "alpha":
            changed = b"public synthetic unreadable-record fixture"
        else:
            store = json.loads(backup.read_bytes())
            store["profiles"][0]["settings"]["endpoint"] = "http://127.0.0.1:46083/v1"
            changed = json.dumps(store).encode()
        profiles.write_bytes(changed)
        write(fault_receipt, {"faultSha256": sha(profiles), "kind": "unreadable-record" if name == "alpha" else "stale-origin"}, exclusive=True)
    else:
        if sha(profiles) != read(fault_receipt)["faultSha256"]:
            raise ValueError("Unexpected external record changed; refuse restoration")
        profiles.write_bytes(backup.read_bytes())
        write(restored_receipt, {"restoredSha256": sha(profiles)}, exclusive=True)
    print(json.dumps({"action": action, "step": name, "completed": True}))

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("action", choices=["prepare", "build", "launch", "corrupt", "restore", "confirm-reload", "native-clock"])
    parser.add_argument("--phase", type=int, choices=[1, 2])
    parser.add_argument("--run", type=int)
    parser.add_argument("--build", type=int, choices=range(1,13))
    parser.add_argument("--acceptance", action="store_true", help="Select proposed build 3/run 6-7 namespace; requires separate native approval")
    parser.add_argument("--combined-attempts", type=int, choices=[3,10], default=3,
                        help="Explicit approved step-3 combined build/launch cap; never resets consumed attempts")
    parser.add_argument("--replacement", action="store_true", help="Explicit approved build 5/run 8-9 and second-root selection")
    parser.add_argument("--preserve-owned-prior", action="store_true", help="Preserve the exactly validated failed timing fixture without accessing or recovering its credentials")
    parser.add_argument("--sequence", type=int, help="Fresh even phase-1 run identity under the same cumulative allowance")
    parser.add_argument("--step", choices=["alpha", "cancel"])
    parser.add_argument("--entry-start-seconds", type=float)
    parser.add_argument("--resume-partial-entry", action="store_true")
    parser.add_argument("--cancel-only", action="store_true")
    parser.add_argument("--completion-run", type=int, choices=[16,17,18], help="Approved phase-2-only completion using run-14 evidence")
    args = parser.parse_args()
    if args.acceptance: select_acceptance(args.combined_attempts, args.replacement, args.sequence)
    elif args.combined_attempts != 3 or args.replacement or args.sequence is not None: parser.error("Combined/replacement allowance is acceptance-only")
    if args.completion_run is not None:
        if not args.acceptance or args.sequence != 14 or not args.replacement:
            parser.error("Completion requires explicit acceptance/replacement/sequence 14")
        COMPLETION_RUN = args.completion_run
        RUN_SECONDS = 1800
    if args.preserve_owned_prior and args.action != "prepare": parser.error("Prior preservation is preparation-only")
    if args.action == "prepare": prepare(args.preserve_owned_prior)
    elif args.action == "build": build(args.build)
    elif args.action == "launch": launch(args.phase, args.run, args.build, args.resume_partial_entry, args.cancel_only)
    elif args.action == "confirm-reload": confirm_reload()
    elif args.action == "native-clock": print(json.dumps(native_input_clock(args.run,args.entry_start_seconds)))
    else: fault(args.action, args.step)
